//----------------------------------------------------------------------------
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
//----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace Webbed.Scripting.Interop
{
    // DEBUG: typedef struct _WebKitViewportAttributesPrivate WebKitViewportAttributesPrivate
    // DEBUG: struct _WebKitViewportAttributesPrivate
    [StructLayout(LayoutKind.Explicit, Size = 0)]
    public unsafe struct _WebKitViewportAttributesPrivate
    {
    }

    // DEBUG: struct _WebKitViewportAttributes { GObject parent_instance; /*< private >*/ WebKitViewportAttributesPrivate *priv;}
    [StructLayout(LayoutKind.Explicit, Size = 16)]
    public unsafe struct _WebKitViewportAttributes
    {
        // DEBUG: GObject parent_instance
        [FieldOffset(0)]
        public _GObject parent_instance;

        // DEBUG: WebKitViewportAttributesPrivate *priv
        [FieldOffset(12)]
        public global::System.IntPtr priv;
    }

    // DEBUG: struct _WebKitViewportAttributesClass { GObjectClass parent_class; /* Padding for future expansion */ void (*_webkit_reserved0) (void); void (*_webkit_reserved1) (void); void (*_webkit_reserved2) (void); void (*_webkit_reserved3) (void);}
    [StructLayout(LayoutKind.Explicit, Size = 84)]
    public unsafe struct _WebKitViewportAttributesClass
    {
        // DEBUG: GObjectClass parent_class
        [FieldOffset(0)]
        public _GObjectClass parent_class;
    }

    public unsafe partial class WebKitViewportAttributes : GLib.Object
    {
        public WebKitViewportAttributes(IntPtr handle) : base(handle) { }
        // DEBUG: WEBKIT_API GTypewebkit_viewport_attributes_get_type (void)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_viewport_attributes_get_type")]
        internal static extern uint webkit_viewport_attributes_get_type();

        public GLib.GType Type
        {
            get
            {
                return new GLib.GType((IntPtr)webkit_viewport_attributes_get_type());
            }
        }

        // DEBUG: WEBKIT_API voidwebkit_viewport_attributes_recompute(WebKitViewportAttributes* viewportAttributes)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_viewport_attributes_recompute")]
        internal static extern void webkit_viewport_attributes_recompute(global::System.IntPtr viewportAttributes);

        public void Recompute()
        {
            webkit_viewport_attributes_recompute(this.Handle);
        }
    }
}
