//----------------------------------------------------------------------------
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
//----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace Webbed.Scripting.Interop
{
    public unsafe partial class WebkitVersion
    {
        // DEBUG: WEBKIT_API guintwebkit_major_version (void)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_major_version")]
        internal static extern uint webkit_major_version();

        public uint MajorVersion()
        {
            return webkit_major_version();
        }

        // DEBUG: WEBKIT_API guintwebkit_minor_version (void)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_minor_version")]
        internal static extern uint webkit_minor_version();

        public uint MinorVersion()
        {
            return webkit_minor_version();
        }

        // DEBUG: WEBKIT_API guintwebkit_micro_version (void)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_micro_version")]
        internal static extern uint webkit_micro_version();

        public uint MicroVersion()
        {
            return webkit_micro_version();
        }

        // DEBUG: WEBKIT_API gbooleanwebkit_check_version (guint major, guint minor, guint micro)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_check_version")]
        internal static extern bool webkit_check_version(uint major, uint minor, uint micro);

        public bool CheckVersion(uint major, uint minor, uint micro)
        {
            return webkit_check_version(major, minor, micro);
        }
    }
}
