//----------------------------------------------------------------------------
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
//----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace Webbed.Scripting.Interop
{
    // DEBUG: enum { WEBKIT_WEB_NAVIGATION_REASON_LINK_CLICKED, WEBKIT_WEB_NAVIGATION_REASON_FORM_SUBMITTED, WEBKIT_WEB_NAVIGATION_REASON_BACK_FORWARD, WEBKIT_WEB_NAVIGATION_REASON_RELOAD, WEBKIT_WEB_NAVIGATION_REASON_FORM_RESUBMITTED, WEBKIT_WEB_NAVIGATION_REASON_OTHER,}
    /// <summary>
    /// <para>WebKitWebNavigationReason: _WEB_NAVIGATION_REASON_LINK_CLICKED:
    /// The navigation was triggered by clicking a link.
    /// _WEB_NAVIGATION_REASON_FORM_SUBMITTED: The navigation was triggered by
    /// submitting a form. _WEB_NAVIGATION_REASON_BACK_FORWARD: The navigation was
    /// triggered by navigating forward or backward. _WEB_NAVIGATION_REASON_RELOAD:
    /// The navigation was triggered by reloading.
    /// _WEB_NAVIGATION_REASON_FORM_RESUBMITTED: The navigation was triggered by
    /// resubmitting a form. _WEB_NAVIGATION_REASON_OTHER: The navigation was
    /// triggered by some other action.</para>
    /// </summary>
    /// <remarks>
    /// <para>/**</para>
    /// <para> * WebKitWebNavigationReason:</para>
    /// <para> * @WEBKIT_WEB_NAVIGATION_REASON_LINK_CLICKED: The navigation was
    /// triggered by clicking a link.</para>
    /// <para> * @WEBKIT_WEB_NAVIGATION_REASON_FORM_SUBMITTED: The navigation
    /// was triggered by submitting a form.</para>
    /// <para> * @WEBKIT_WEB_NAVIGATION_REASON_BACK_FORWARD: The navigation was
    /// triggered by navigating forward or backward.</para>
    /// <para> * @WEBKIT_WEB_NAVIGATION_REASON_RELOAD: The navigation was
    /// triggered by reloading.</para>
    /// <para> * @WEBKIT_WEB_NAVIGATION_REASON_FORM_RESUBMITTED: The navigation
    /// was triggered by resubmitting a form.</para>
    /// <para> * @WEBKIT_WEB_NAVIGATION_REASON_OTHER: The navigation was
    /// triggered by some other action.</para>
    /// <para> *</para>
    /// <para> * Enum values used to denote the various navigation
    /// reasons.</para>
    /// <para> */</para>
    /// </remarks>
    // DEBUG: enum { WEBKIT_WEB_NAVIGATION_REASON_LINK_CLICKED, WEBKIT_WEB_NAVIGATION_REASON_FORM_SUBMITTED, WEBKIT_WEB_NAVIGATION_REASON_BACK_FORWARD, WEBKIT_WEB_NAVIGATION_REASON_RELOAD, WEBKIT_WEB_NAVIGATION_REASON_FORM_RESUBMITTED, WEBKIT_WEB_NAVIGATION_REASON_OTHER,}
    public enum WebKitWebNavigationReason
    {
        WEBKIT_WEB_NAVIGATION_REASON_LINK_CLICKED = 0,
        WEBKIT_WEB_NAVIGATION_REASON_FORM_SUBMITTED = 1,
        WEBKIT_WEB_NAVIGATION_REASON_BACK_FORWARD = 2,
        WEBKIT_WEB_NAVIGATION_REASON_RELOAD = 3,
        WEBKIT_WEB_NAVIGATION_REASON_FORM_RESUBMITTED = 4,
        WEBKIT_WEB_NAVIGATION_REASON_OTHER = 5
    }

    // DEBUG: typedef enum { WEBKIT_WEB_NAVIGATION_REASON_LINK_CLICKED, WEBKIT_WEB_NAVIGATION_REASON_FORM_SUBMITTED, WEBKIT_WEB_NAVIGATION_REASON_BACK_FORWARD, WEBKIT_WEB_NAVIGATION_REASON_RELOAD, WEBKIT_WEB_NAVIGATION_REASON_FORM_RESUBMITTED, WEBKIT_WEB_NAVIGATION_REASON_OTHER,} WebKitWebNavigationReason
    // DEBUG: typedef struct _WebKitWebNavigationAction WebKitWebNavigationAction
    // DEBUG: typedef struct _WebKitWebNavigationActionPrivate WebKitWebNavigationActionPrivate
    // DEBUG: typedef struct _WebKitWebNavigationActionClass WebKitWebNavigationActionClass
    // DEBUG: struct _WebKitWebNavigationActionPrivate
    [StructLayout(LayoutKind.Explicit, Size = 0)]
    public unsafe struct _WebKitWebNavigationActionPrivate
    {
    }

    // DEBUG: struct _WebKitWebNavigationAction { GObject parent_instance; /*< private >*/ WebKitWebNavigationActionPrivate* priv;}
    [StructLayout(LayoutKind.Explicit, Size = 16)]
    public unsafe struct _WebKitWebNavigationAction
    {
        // DEBUG: GObject parent_instance
        [FieldOffset(0)]
        public _GObject parent_instance;

        // DEBUG: WebKitWebNavigationActionPrivate* priv
        [FieldOffset(12)]
        public global::System.IntPtr priv;
    }

    // DEBUG: struct _WebKitWebNavigationActionClass { GObjectClass parent_class; /* Padding for future expansion */ void (*_webkit_reserved0) (void); void (*_webkit_reserved1) (void); void (*_webkit_reserved2) (void); void (*_webkit_reserved3) (void);}
    [StructLayout(LayoutKind.Explicit, Size = 84)]
    public unsafe struct _WebKitWebNavigationActionClass
    {
        // DEBUG: GObjectClass parent_class
        [FieldOffset(0)]
        public _GObjectClass parent_class;
    }

    public unsafe partial class WebKitWebNavigationAction : GLib.Object
    {
        public WebKitWebNavigationAction(IntPtr handle) : base(handle) { }
        // DEBUG: WEBKIT_API GTypewebkit_web_navigation_action_get_type(void)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_web_navigation_action_get_type")]
        internal static extern uint webkit_web_navigation_action_get_type();
        
        public override GLib.GType Type
        {
            get
            {
                return new GLib.GType((IntPtr)webkit_web_navigation_action_get_type());
            }
        }

        // DEBUG: WEBKIT_API WebKitWebNavigationReasonwebkit_web_navigation_action_get_reason(WebKitWebNavigationAction* navigationAction)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_web_navigation_action_get_reason")]
        internal static extern WebKitWebNavigationReason webkit_web_navigation_action_get_reason(global::System.IntPtr navigationAction);

        public WebKitWebNavigationReason Reason
        {
            get{
                return webkit_web_navigation_action_get_reason(this.Handle);
            }
            set
            {
                webkit_web_navigation_action_set_reason(this.Handle, value);
            }
        }

        // DEBUG: WEBKIT_API voidwebkit_web_navigation_action_set_reason(WebKitWebNavigationAction* navigationAction, WebKitWebNavigationReason reason)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_web_navigation_action_set_reason")]
        internal static extern void webkit_web_navigation_action_set_reason(global::System.IntPtr navigationAction, WebKitWebNavigationReason reason);

        // DEBUG: WEBKIT_API const gchar*webkit_web_navigation_action_get_original_uri(WebKitWebNavigationAction* navigationAction)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl, CharSet=CharSet.Ansi,
            EntryPoint="webkit_web_navigation_action_get_original_uri")]
        internal static extern string webkit_web_navigation_action_get_original_uri(global::System.IntPtr navigationAction);

        // DEBUG: WEBKIT_API voidwebkit_web_navigation_action_set_original_uri(WebKitWebNavigationAction* navigationAction, const gchar* originalUri)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl, CharSet = CharSet.Ansi,
            EntryPoint="webkit_web_navigation_action_set_original_uri")]
        internal static extern void webkit_web_navigation_action_set_original_uri(global::System.IntPtr navigationAction, string originalUri);

        public string OriginalUri
        {
            get
            {
                webkit_web_navigation_action_get_original_uri(this.Handle);
            }
            set
            {
                webkit_web_navigation_action_set_original_uri(this.Handle, value);
            }
        }

        // DEBUG: WEBKIT_API gintwebkit_web_navigation_action_get_button(WebKitWebNavigationAction* navigationAction)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_web_navigation_action_get_button")]
        internal static extern int webkit_web_navigation_action_get_button(global::System.IntPtr navigationAction);

        public int Button
        {
            get
            {
                return webkit_web_navigation_action_get_button(this.Handle);
            }
        }

        // DEBUG: WEBKIT_API gintwebkit_web_navigation_action_get_modifier_state(WebKitWebNavigationAction* navigationAction)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_web_navigation_action_get_modifier_state")]
        internal static extern int webkit_web_navigation_action_get_modifier_state(global::System.IntPtr navigationAction);
                
        public int ModifierState
        {
            get
            {
                return webkit_web_navigation_action_get_button(this.Handle);
            }
        }

        // DEBUG: WEBKIT_API const gchar *webkit_web_navigation_action_get_target_frame(WebKitWebNavigationAction* navigationAction)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl, CharSet = CharSet.Ansi,
            EntryPoint="webkit_web_navigation_action_get_target_frame")]
        internal static extern string webkit_web_navigation_action_get_target_frame(global::System.IntPtr navigationAction);

        public string TargetFrame
        {
            get{
                return webkit_web_navigation_action_get_target_frame(this.Handle);
            }
        }
    }
}
