//----------------------------------------------------------------------------
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
//----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace Webbed.Scripting.Interop
{
    // DEBUG: typedef struct _WebKitWebDatabasePrivate WebKitWebDatabasePrivate
    // DEBUG: struct _WebKitWebDatabasePrivate
    [StructLayout(LayoutKind.Explicit, Size = 0)]
    public unsafe struct _WebKitWebDatabasePrivate
    {
    }

    // DEBUG: struct _WebKitWebDatabase { GObject parent_instance; /*< private >*/ WebKitWebDatabasePrivate* priv;}
    [StructLayout(LayoutKind.Explicit, Size = 16)]
    public unsafe struct _WebKitWebDatabase
    {
        // DEBUG: GObject parent_instance
        [FieldOffset(0)]
        public _GObject parent_instance;

        // DEBUG: WebKitWebDatabasePrivate* priv
        [FieldOffset(12)]
        public global::System.IntPtr priv;
    }

    // DEBUG: struct _WebKitWebDatabaseClass { GObjectClass parent_class; /* Padding for future expansion */ void (*_webkit_reserved1) (void); void (*_webkit_reserved2) (void); void (*_webkit_reserved3) (void); void (*_webkit_reserved4) (void);}
    [StructLayout(LayoutKind.Explicit, Size = 84)]
    public unsafe struct _WebKitWebDatabaseClass
    {
        // DEBUG: GObjectClass parent_class
        [FieldOffset(0)]
        public _GObjectClass parent_class;
    }

    public unsafe partial class WebKitWebDatabase : GLib.Object
    {
        public WebKitWebDatabase(IntPtr handle):base(handle){};

        // DEBUG: WEBKIT_API GTypewebkit_web_database_get_type (void)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_web_database_get_type")]
        internal static extern uint webkit_web_database_get_type();

        public GLib.GType Type
        {
            get
            {
                return new GLib.GType((IntPtr)webkit_web_database_get_type());
            }
        }
        // DEBUG: WEBKIT_API WebKitSecurityOrigin *webkit_web_database_get_security_origin (WebKitWebDatabase* webDatabase)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_web_database_get_security_origin")]
        internal static extern global::System.IntPtr webkit_web_database_get_security_origin(global::System.IntPtr webDatabase);

        public WebKitSecurityOrigin SecurityOrigin
        {
            get
            {
                return new WebKitSecurityOrigin(webkit_web_database_get_security_origin(this.Handle));
            }
        }

        // DEBUG: WEBKIT_API const gchar*webkit_web_database_get_name (WebKitWebDatabase* webDatabase)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl, CharSet=CharSet.Ansi,
            EntryPoint="webkit_web_database_get_name")]
        internal static extern string webkit_web_database_get_name(global::System.IntPtr webDatabase);

        public string Name{
            get{
                return webkit_web_database_get_name(this.Handle);
            }
        }

        // DEBUG: WEBKIT_API const gchar*webkit_web_database_get_display_name (WebKitWebDatabase* webDatabase)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl, CharSet=CharSet.Ansi,
            EntryPoint="webkit_web_database_get_display_name")]
        internal static extern string webkit_web_database_get_display_name(global::System.IntPtr webDatabase);

        public string DisplayName{
            get{
                return webkit_web_database_get_display_name(this.Handle);
            }
        }

        // DEBUG: WEBKIT_API guint64webkit_web_database_get_expected_size (WebKitWebDatabase* webDatabase)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_web_database_get_expected_size")]
        internal static extern ulong webkit_web_database_get_expected_size(global::System.IntPtr webDatabase);

        public ulong ExpectedSize{
            get{
                return webkit_web_database_get_expected_size(this.Handle);
            }
        }

        // DEBUG: WEBKIT_API guint64webkit_web_database_get_size (WebKitWebDatabase* webDatabase)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_web_database_get_size")]
        internal static extern ulong webkit_web_database_get_size(global::System.IntPtr webDatabase);

        public ulong Size{
            get{
                return webkit_web_database_get_size(this.Handle);
            }
        }

        // DEBUG: WEBKIT_API const gchar*webkit_web_database_get_filename (WebKitWebDatabase* webDatabase)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl, CharSet=CharSet.Ansi,
            EntryPoint="webkit_web_database_get_filename")]
        internal static extern string webkit_web_database_get_filename(global::System.IntPtr webDatabase);

        public string FileName{
            get{
                return webkit_web_database_get_filename(this.Handle);
            }
        }

        // DEBUG: WEBKIT_API voidwebkit_web_database_remove (WebKitWebDatabase* webDatabase)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_web_database_remove")]
        internal static extern void webkit_web_database_remove(global::System.IntPtr webDatabase);

        public void Remove(){
            webkit_web_database_remove(this.Handle);
        }

        // DEBUG: WEBKIT_API voidwebkit_remove_all_web_databases (void)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_remove_all_web_databases")]
        internal static extern void webkit_remove_all_web_databases();

        public void RemoveAll(){
            webkit_remove_all_web_databases();
        }

        // DEBUG: WEBKIT_API const gchar*webkit_get_web_database_directory_path (void)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,CharSet=CharSet.Ansi,
            EntryPoint="webkit_get_web_database_directory_path")]
        internal static extern string webkit_get_web_database_directory_path();

        public static string DirectoryPath{
            get{
                return webkit_get_web_database_directory_path();
            }set{
                webkit_set_web_database_directory_path(value);
            }
        }

        // DEBUG: WEBKIT_API voidwebkit_set_web_database_directory_path (const gchar* path)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,CharSet=CharSet.Ansi,
            EntryPoint="webkit_set_web_database_directory_path")]
        internal static extern void webkit_set_web_database_directory_path(global::System.IntPtr path);

        // DEBUG: WEBKIT_API guint64webkit_get_default_web_database_quota (void)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_get_default_web_database_quota")]
        internal static extern ulong webkit_get_default_web_database_quota();

        public static ulong DefaultQuota{
            get{
                return webkit_get_default_web_database_quota();
            }set{
                webkit_set_default_web_database_quota(value);
            }
        }

        // DEBUG: WEBKIT_API voidwebkit_set_default_web_database_quota (guint64 defaultQuota)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_set_default_web_database_quota")]
        internal static extern void webkit_set_default_web_database_quota(ulong defaultQuota);
    }
}
