//----------------------------------------------------------------------------
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
//----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace Webbed.Scripting.Interop
{
    public unsafe partial class WebKitDOMCustom: GLib.Object
    {
        public WebKitDOMCustom(IntPtr handle) : base(handle) { }
        // DEBUG: WEBKIT_API gboolean webkit_dom_html_text_area_element_is_edited(WebKitDOMHTMLTextAreaElement*)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_text_area_element_is_edited")]
        internal static extern int webkit_dom_html_text_area_element_is_edited(global::System.IntPtr _0);

        // DEBUG: WEBKIT_API gboolean webkit_dom_html_input_element_is_edited(WebKitDOMHTMLInputElement*)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_input_element_is_edited")]
        internal static extern int webkit_dom_html_input_element_is_edited(global::System.IntPtr _0);

        // DEBUG: WEBKIT_API WebKitDOMBlob* webkit_dom_blob_slice(WebKitDOMBlob* self, gint64 start, gint64 end, const gchar* content_type)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_blob_slice")]
        internal static extern global::System.IntPtr webkit_dom_blob_slice(global::System.IntPtr self, long start, long end, global::System.IntPtr content_type);

        // DEBUG: WEBKIT_API void webkit_dom_html_form_element_dispatch_form_change(WebKitDOMHTMLFormElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_form_element_dispatch_form_change")]
        internal static extern void webkit_dom_html_form_element_dispatch_form_change(global::System.IntPtr self);

        // DEBUG: WEBKIT_API void webkit_dom_html_form_element_dispatch_form_input(WebKitDOMHTMLFormElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_form_element_dispatch_form_input")]
        internal static extern void webkit_dom_html_form_element_dispatch_form_input(global::System.IntPtr self);
    }
}
