//----------------------------------------------------------------------------
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
//----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace Webbed.Scripting.Interop
{
    // DEBUG: struct _WebKitDOMHTMLFontElement { WebKitDOMHTMLElement parent_instance;}
    [StructLayout(LayoutKind.Explicit, Size = 16)]
    public unsafe struct _WebKitDOMHTMLFontElement
    {
        // DEBUG: WebKitDOMHTMLElement parent_instance
        [FieldOffset(0)]
        public _WebKitDOMHTMLElement parent_instance;
    }

    // DEBUG: struct _WebKitDOMHTMLFontElementClass { WebKitDOMHTMLElementClass parent_class;}
    [StructLayout(LayoutKind.Explicit, Size = 68)]
    public unsafe struct _WebKitDOMHTMLFontElementClass
    {
        // DEBUG: WebKitDOMHTMLElementClass parent_class
        [FieldOffset(0)]
        public _WebKitDOMHTMLElementClass parent_class;
    }

    public unsafe partial class WebKitDOMHTMLFontElement: GLib.Object
    {
        public WebKitDOMHTMLFontElement(IntPtr handle) : base(handle) { }
        // DEBUG: WEBKIT_API GTypewebkit_dom_html_font_element_get_type (void)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_font_element_get_type")]
        internal static extern uint webkit_dom_html_font_element_get_type();
        public GLib.GType Type
        {
            get
            {
                return new GLib.GType((IntPtr)webkit_dom_html_font_element_get_type());
            }
        }

        // DEBUG: WEBKIT_API gchar*webkit_dom_html_font_element_get_color(WebKitDOMHTMLFontElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_font_element_get_color")]
        internal static extern sbyte* webkit_dom_html_font_element_get_color(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_font_element_set_color(WebKitDOMHTMLFontElement* self, const gchar* value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_font_element_set_color")]
        internal static extern void webkit_dom_html_font_element_set_color(global::System.IntPtr self, global::System.IntPtr value);

        // DEBUG: WEBKIT_API gchar*webkit_dom_html_font_element_get_face(WebKitDOMHTMLFontElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_font_element_get_face")]
        internal static extern sbyte* webkit_dom_html_font_element_get_face(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_font_element_set_face(WebKitDOMHTMLFontElement* self, const gchar* value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_font_element_set_face")]
        internal static extern void webkit_dom_html_font_element_set_face(global::System.IntPtr self, global::System.IntPtr value);

        // DEBUG: WEBKIT_API gchar*webkit_dom_html_font_element_get_size(WebKitDOMHTMLFontElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_font_element_get_size")]
        internal static extern sbyte* webkit_dom_html_font_element_get_size(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_font_element_set_size(WebKitDOMHTMLFontElement* self, const gchar* value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_font_element_set_size")]
        internal static extern void webkit_dom_html_font_element_set_size(global::System.IntPtr self, global::System.IntPtr value);
    }
}
