//----------------------------------------------------------------------------
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
//----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace Webbed.Scripting.Interop
{
    // DEBUG: struct _WebKitDOMHTMLAnchorElement { WebKitDOMHTMLElement parent_instance;}
    [StructLayout(LayoutKind.Explicit, Size = 16)]
    public unsafe struct _WebKitDOMHTMLAnchorElement
    {
        // DEBUG: WebKitDOMHTMLElement parent_instance
        [FieldOffset(0)]
        public _WebKitDOMHTMLElement parent_instance;
    }

    // DEBUG: struct _WebKitDOMHTMLAnchorElementClass { WebKitDOMHTMLElementClass parent_class;}
    [StructLayout(LayoutKind.Explicit, Size = 68)]
    public unsafe struct _WebKitDOMHTMLAnchorElementClass
    {
        // DEBUG: WebKitDOMHTMLElementClass parent_class
        [FieldOffset(0)]
        public _WebKitDOMHTMLElementClass parent_class;
    }

    public unsafe partial class WebKitDOMHTMLAnchorElement: GLib.Object
    {
        public WebKitDOMHTMLAnchorElement(IntPtr handle) : base(handle) { }
        // DEBUG: WEBKIT_API GTypewebkit_dom_html_anchor_element_get_type (void)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_anchor_element_get_type")]
        internal static extern uint webkit_dom_html_anchor_element_get_type();
        public GLib.GType Type
        {
            get
            {
                return new GLib.GType((IntPtr)webkit_dom_html_anchor_element_get_type());
            }
        }

        // DEBUG: WEBKIT_API gchar*webkit_dom_html_anchor_element_get_charset(WebKitDOMHTMLAnchorElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_anchor_element_get_charset")]
        internal static extern sbyte* webkit_dom_html_anchor_element_get_charset(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_anchor_element_set_charset(WebKitDOMHTMLAnchorElement* self, const gchar* value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_anchor_element_set_charset")]
        internal static extern void webkit_dom_html_anchor_element_set_charset(global::System.IntPtr self, global::System.IntPtr value);

        // DEBUG: WEBKIT_API gchar*webkit_dom_html_anchor_element_get_coords(WebKitDOMHTMLAnchorElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_anchor_element_get_coords")]
        internal static extern sbyte* webkit_dom_html_anchor_element_get_coords(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_anchor_element_set_coords(WebKitDOMHTMLAnchorElement* self, const gchar* value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_anchor_element_set_coords")]
        internal static extern void webkit_dom_html_anchor_element_set_coords(global::System.IntPtr self, global::System.IntPtr value);

        // DEBUG: WEBKIT_API gchar*webkit_dom_html_anchor_element_get_download(WebKitDOMHTMLAnchorElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_anchor_element_get_download")]
        internal static extern sbyte* webkit_dom_html_anchor_element_get_download(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_anchor_element_set_download(WebKitDOMHTMLAnchorElement* self, const gchar* value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_anchor_element_set_download")]
        internal static extern void webkit_dom_html_anchor_element_set_download(global::System.IntPtr self, global::System.IntPtr value);

        // DEBUG: WEBKIT_API gchar*webkit_dom_html_anchor_element_get_href(WebKitDOMHTMLAnchorElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_anchor_element_get_href")]
        internal static extern sbyte* webkit_dom_html_anchor_element_get_href(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_anchor_element_set_href(WebKitDOMHTMLAnchorElement* self, const gchar* value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_anchor_element_set_href")]
        internal static extern void webkit_dom_html_anchor_element_set_href(global::System.IntPtr self, global::System.IntPtr value);

        // DEBUG: WEBKIT_API gchar*webkit_dom_html_anchor_element_get_hreflang(WebKitDOMHTMLAnchorElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_anchor_element_get_hreflang")]
        internal static extern sbyte* webkit_dom_html_anchor_element_get_hreflang(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_anchor_element_set_hreflang(WebKitDOMHTMLAnchorElement* self, const gchar* value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_anchor_element_set_hreflang")]
        internal static extern void webkit_dom_html_anchor_element_set_hreflang(global::System.IntPtr self, global::System.IntPtr value);

        // DEBUG: WEBKIT_API gchar*webkit_dom_html_anchor_element_get_name(WebKitDOMHTMLAnchorElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_anchor_element_get_name")]
        internal static extern sbyte* webkit_dom_html_anchor_element_get_name(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_anchor_element_set_name(WebKitDOMHTMLAnchorElement* self, const gchar* value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_anchor_element_set_name")]
        internal static extern void webkit_dom_html_anchor_element_set_name(global::System.IntPtr self, global::System.IntPtr value);

        // DEBUG: WEBKIT_API gchar*webkit_dom_html_anchor_element_get_ping(WebKitDOMHTMLAnchorElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_anchor_element_get_ping")]
        internal static extern sbyte* webkit_dom_html_anchor_element_get_ping(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_anchor_element_set_ping(WebKitDOMHTMLAnchorElement* self, const gchar* value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_anchor_element_set_ping")]
        internal static extern void webkit_dom_html_anchor_element_set_ping(global::System.IntPtr self, global::System.IntPtr value);

        // DEBUG: WEBKIT_API gchar*webkit_dom_html_anchor_element_get_rel(WebKitDOMHTMLAnchorElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_anchor_element_get_rel")]
        internal static extern sbyte* webkit_dom_html_anchor_element_get_rel(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_anchor_element_set_rel(WebKitDOMHTMLAnchorElement* self, const gchar* value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_anchor_element_set_rel")]
        internal static extern void webkit_dom_html_anchor_element_set_rel(global::System.IntPtr self, global::System.IntPtr value);

        // DEBUG: WEBKIT_API gchar*webkit_dom_html_anchor_element_get_rev(WebKitDOMHTMLAnchorElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_anchor_element_get_rev")]
        internal static extern sbyte* webkit_dom_html_anchor_element_get_rev(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_anchor_element_set_rev(WebKitDOMHTMLAnchorElement* self, const gchar* value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_anchor_element_set_rev")]
        internal static extern void webkit_dom_html_anchor_element_set_rev(global::System.IntPtr self, global::System.IntPtr value);

        // DEBUG: WEBKIT_API gchar*webkit_dom_html_anchor_element_get_shape(WebKitDOMHTMLAnchorElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_anchor_element_get_shape")]
        internal static extern sbyte* webkit_dom_html_anchor_element_get_shape(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_anchor_element_set_shape(WebKitDOMHTMLAnchorElement* self, const gchar* value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_anchor_element_set_shape")]
        internal static extern void webkit_dom_html_anchor_element_set_shape(global::System.IntPtr self, global::System.IntPtr value);

        // DEBUG: WEBKIT_API gchar*webkit_dom_html_anchor_element_get_target(WebKitDOMHTMLAnchorElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_anchor_element_get_target")]
        internal static extern sbyte* webkit_dom_html_anchor_element_get_target(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_anchor_element_set_target(WebKitDOMHTMLAnchorElement* self, const gchar* value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_anchor_element_set_target")]
        internal static extern void webkit_dom_html_anchor_element_set_target(global::System.IntPtr self, global::System.IntPtr value);

        // DEBUG: WEBKIT_API gchar*webkit_dom_html_anchor_element_get_hash(WebKitDOMHTMLAnchorElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_anchor_element_get_hash")]
        internal static extern sbyte* webkit_dom_html_anchor_element_get_hash(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_anchor_element_set_hash(WebKitDOMHTMLAnchorElement* self, const gchar* value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_anchor_element_set_hash")]
        internal static extern void webkit_dom_html_anchor_element_set_hash(global::System.IntPtr self, global::System.IntPtr value);

        // DEBUG: WEBKIT_API gchar*webkit_dom_html_anchor_element_get_host(WebKitDOMHTMLAnchorElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_anchor_element_get_host")]
        internal static extern sbyte* webkit_dom_html_anchor_element_get_host(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_anchor_element_set_host(WebKitDOMHTMLAnchorElement* self, const gchar* value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_anchor_element_set_host")]
        internal static extern void webkit_dom_html_anchor_element_set_host(global::System.IntPtr self, global::System.IntPtr value);

        // DEBUG: WEBKIT_API gchar*webkit_dom_html_anchor_element_get_hostname(WebKitDOMHTMLAnchorElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_anchor_element_get_hostname")]
        internal static extern sbyte* webkit_dom_html_anchor_element_get_hostname(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_anchor_element_set_hostname(WebKitDOMHTMLAnchorElement* self, const gchar* value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_anchor_element_set_hostname")]
        internal static extern void webkit_dom_html_anchor_element_set_hostname(global::System.IntPtr self, global::System.IntPtr value);

        // DEBUG: WEBKIT_API gchar*webkit_dom_html_anchor_element_get_pathname(WebKitDOMHTMLAnchorElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_anchor_element_get_pathname")]
        internal static extern sbyte* webkit_dom_html_anchor_element_get_pathname(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_anchor_element_set_pathname(WebKitDOMHTMLAnchorElement* self, const gchar* value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_anchor_element_set_pathname")]
        internal static extern void webkit_dom_html_anchor_element_set_pathname(global::System.IntPtr self, global::System.IntPtr value);

        // DEBUG: WEBKIT_API gchar*webkit_dom_html_anchor_element_get_port(WebKitDOMHTMLAnchorElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_anchor_element_get_port")]
        internal static extern sbyte* webkit_dom_html_anchor_element_get_port(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_anchor_element_set_port(WebKitDOMHTMLAnchorElement* self, const gchar* value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_anchor_element_set_port")]
        internal static extern void webkit_dom_html_anchor_element_set_port(global::System.IntPtr self, global::System.IntPtr value);

        // DEBUG: WEBKIT_API gchar*webkit_dom_html_anchor_element_get_protocol(WebKitDOMHTMLAnchorElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_anchor_element_get_protocol")]
        internal static extern sbyte* webkit_dom_html_anchor_element_get_protocol(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_anchor_element_set_protocol(WebKitDOMHTMLAnchorElement* self, const gchar* value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_anchor_element_set_protocol")]
        internal static extern void webkit_dom_html_anchor_element_set_protocol(global::System.IntPtr self, global::System.IntPtr value);

        // DEBUG: WEBKIT_API gchar*webkit_dom_html_anchor_element_get_search(WebKitDOMHTMLAnchorElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_anchor_element_get_search")]
        internal static extern sbyte* webkit_dom_html_anchor_element_get_search(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_anchor_element_set_search(WebKitDOMHTMLAnchorElement* self, const gchar* value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_anchor_element_set_search")]
        internal static extern void webkit_dom_html_anchor_element_set_search(global::System.IntPtr self, global::System.IntPtr value);

        // DEBUG: WEBKIT_API gchar*webkit_dom_html_anchor_element_get_origin(WebKitDOMHTMLAnchorElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_anchor_element_get_origin")]
        internal static extern sbyte* webkit_dom_html_anchor_element_get_origin(global::System.IntPtr self);

        // DEBUG: WEBKIT_API gchar*webkit_dom_html_anchor_element_get_text(WebKitDOMHTMLAnchorElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_anchor_element_get_text")]
        internal static extern sbyte* webkit_dom_html_anchor_element_get_text(global::System.IntPtr self);
    }
}
