//----------------------------------------------------------------------------
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
//----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace Webbed.Scripting.Interop
{
    // DEBUG: struct _WebKitDOMHTMLSelectElement { WebKitDOMHTMLElement parent_instance;}
    [StructLayout(LayoutKind.Explicit, Size = 16)]
    public unsafe struct _WebKitDOMHTMLSelectElement
    {
        // DEBUG: WebKitDOMHTMLElement parent_instance
        [FieldOffset(0)]
        public _WebKitDOMHTMLElement parent_instance;
    }

    // DEBUG: struct _WebKitDOMHTMLSelectElementClass { WebKitDOMHTMLElementClass parent_class;}
    [StructLayout(LayoutKind.Explicit, Size = 68)]
    public unsafe struct _WebKitDOMHTMLSelectElementClass
    {
        // DEBUG: WebKitDOMHTMLElementClass parent_class
        [FieldOffset(0)]
        public _WebKitDOMHTMLElementClass parent_class;
    }

    public unsafe partial class WebKitDOMHTMLSelectElement: GLib.Object
    {
        public WebKitDOMHTMLSelectElement(IntPtr handle) : base(handle) { }
        // DEBUG: WEBKIT_API GTypewebkit_dom_html_select_element_get_type (void)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_select_element_get_type")]
        internal static extern uint webkit_dom_html_select_element_get_type();
        public GLib.GType Type
        {
            get
            {
                return new GLib.GType((IntPtr)webkit_dom_html_select_element_get_type());
            }
        }

        // DEBUG: WEBKIT_API gbooleanwebkit_dom_html_select_element_check_validity(WebKitDOMHTMLSelectElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_select_element_check_validity")]
        internal static extern int webkit_dom_html_select_element_check_validity(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_select_element_set_custom_validity(WebKitDOMHTMLSelectElement* self, const gchar* error)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_select_element_set_custom_validity")]
        internal static extern void webkit_dom_html_select_element_set_custom_validity(global::System.IntPtr self, global::System.IntPtr error);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_select_element_add(WebKitDOMHTMLSelectElement* self, WebKitDOMHTMLElement* element, WebKitDOMHTMLElement* before, GError **error)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_select_element_add")]
        internal static extern void webkit_dom_html_select_element_add(global::System.IntPtr self, global::System.IntPtr element, global::System.IntPtr before, global::System.IntPtr error);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_select_element_remove(WebKitDOMHTMLSelectElement* self, glong index)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_select_element_remove")]
        internal static extern void webkit_dom_html_select_element_remove(global::System.IntPtr self, int index);

        // DEBUG: WEBKIT_API WebKitDOMNode*webkit_dom_html_select_element_item(WebKitDOMHTMLSelectElement* self, gulong index)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_select_element_item")]
        internal static extern global::System.IntPtr webkit_dom_html_select_element_item(global::System.IntPtr self, uint index);

        // DEBUG: WEBKIT_API WebKitDOMNode*webkit_dom_html_select_element_named_item(WebKitDOMHTMLSelectElement* self, const gchar* name)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_select_element_named_item")]
        internal static extern global::System.IntPtr webkit_dom_html_select_element_named_item(global::System.IntPtr self, global::System.IntPtr name);

        // DEBUG: WEBKIT_API glongwebkit_dom_html_select_element_get_selected_index(WebKitDOMHTMLSelectElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_select_element_get_selected_index")]
        internal static extern int webkit_dom_html_select_element_get_selected_index(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_select_element_set_selected_index(WebKitDOMHTMLSelectElement* self, glong value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_select_element_set_selected_index")]
        internal static extern void webkit_dom_html_select_element_set_selected_index(global::System.IntPtr self, int value);

        // DEBUG: WEBKIT_API gchar*webkit_dom_html_select_element_get_value(WebKitDOMHTMLSelectElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_select_element_get_value")]
        internal static extern sbyte* webkit_dom_html_select_element_get_value(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_select_element_set_value(WebKitDOMHTMLSelectElement* self, const gchar* value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_select_element_set_value")]
        internal static extern void webkit_dom_html_select_element_set_value(global::System.IntPtr self, global::System.IntPtr value);

        // DEBUG: WEBKIT_API gulongwebkit_dom_html_select_element_get_length(WebKitDOMHTMLSelectElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_select_element_get_length")]
        internal static extern uint webkit_dom_html_select_element_get_length(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_select_element_set_length(WebKitDOMHTMLSelectElement* self, gulong value, GError **error)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_select_element_set_length")]
        internal static extern void webkit_dom_html_select_element_set_length(global::System.IntPtr self, uint value, global::System.IntPtr error);

        // DEBUG: WEBKIT_API WebKitDOMHTMLFormElement*webkit_dom_html_select_element_get_form(WebKitDOMHTMLSelectElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_select_element_get_form")]
        internal static extern global::System.IntPtr webkit_dom_html_select_element_get_form(global::System.IntPtr self);

        // DEBUG: WEBKIT_API WebKitDOMValidityState*webkit_dom_html_select_element_get_validity(WebKitDOMHTMLSelectElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_select_element_get_validity")]
        internal static extern global::System.IntPtr webkit_dom_html_select_element_get_validity(global::System.IntPtr self);

        // DEBUG: WEBKIT_API gbooleanwebkit_dom_html_select_element_get_will_validate(WebKitDOMHTMLSelectElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_select_element_get_will_validate")]
        internal static extern int webkit_dom_html_select_element_get_will_validate(global::System.IntPtr self);

        // DEBUG: WEBKIT_API gchar*webkit_dom_html_select_element_get_validation_message(WebKitDOMHTMLSelectElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_select_element_get_validation_message")]
        internal static extern sbyte* webkit_dom_html_select_element_get_validation_message(global::System.IntPtr self);

        // DEBUG: WEBKIT_API WebKitDOMHTMLOptionsCollection*webkit_dom_html_select_element_get_options(WebKitDOMHTMLSelectElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_select_element_get_options")]
        internal static extern global::System.IntPtr webkit_dom_html_select_element_get_options(global::System.IntPtr self);

        // DEBUG: WEBKIT_API gbooleanwebkit_dom_html_select_element_get_disabled(WebKitDOMHTMLSelectElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_select_element_get_disabled")]
        internal static extern int webkit_dom_html_select_element_get_disabled(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_select_element_set_disabled(WebKitDOMHTMLSelectElement* self, gboolean value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_select_element_set_disabled")]
        internal static extern void webkit_dom_html_select_element_set_disabled(global::System.IntPtr self, int value);

        // DEBUG: WEBKIT_API gbooleanwebkit_dom_html_select_element_get_autofocus(WebKitDOMHTMLSelectElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_select_element_get_autofocus")]
        internal static extern int webkit_dom_html_select_element_get_autofocus(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_select_element_set_autofocus(WebKitDOMHTMLSelectElement* self, gboolean value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_select_element_set_autofocus")]
        internal static extern void webkit_dom_html_select_element_set_autofocus(global::System.IntPtr self, int value);

        // DEBUG: WEBKIT_API gbooleanwebkit_dom_html_select_element_get_multiple(WebKitDOMHTMLSelectElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_select_element_get_multiple")]
        internal static extern int webkit_dom_html_select_element_get_multiple(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_select_element_set_multiple(WebKitDOMHTMLSelectElement* self, gboolean value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_select_element_set_multiple")]
        internal static extern void webkit_dom_html_select_element_set_multiple(global::System.IntPtr self, int value);

        // DEBUG: WEBKIT_API gchar*webkit_dom_html_select_element_get_name(WebKitDOMHTMLSelectElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_select_element_get_name")]
        internal static extern sbyte* webkit_dom_html_select_element_get_name(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_select_element_set_name(WebKitDOMHTMLSelectElement* self, const gchar* value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_select_element_set_name")]
        internal static extern void webkit_dom_html_select_element_set_name(global::System.IntPtr self, global::System.IntPtr value);

        // DEBUG: WEBKIT_API gbooleanwebkit_dom_html_select_element_get_required(WebKitDOMHTMLSelectElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_select_element_get_required")]
        internal static extern int webkit_dom_html_select_element_get_required(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_select_element_set_required(WebKitDOMHTMLSelectElement* self, gboolean value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_select_element_set_required")]
        internal static extern void webkit_dom_html_select_element_set_required(global::System.IntPtr self, int value);

        // DEBUG: WEBKIT_API glongwebkit_dom_html_select_element_get_size(WebKitDOMHTMLSelectElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_select_element_get_size")]
        internal static extern int webkit_dom_html_select_element_get_size(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_select_element_set_size(WebKitDOMHTMLSelectElement* self, glong value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_select_element_set_size")]
        internal static extern void webkit_dom_html_select_element_set_size(global::System.IntPtr self, int value);

        // DEBUG: WEBKIT_API WebKitDOMNodeList*webkit_dom_html_select_element_get_labels(WebKitDOMHTMLSelectElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_select_element_get_labels")]
        internal static extern global::System.IntPtr webkit_dom_html_select_element_get_labels(global::System.IntPtr self);
    }
}
