//----------------------------------------------------------------------------
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
//----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace Webbed.Scripting.Interop
{
    // DEBUG: struct _WebKitDOMHTMLScriptElement { WebKitDOMHTMLElement parent_instance;}
    [StructLayout(LayoutKind.Explicit, Size = 16)]
    public unsafe struct _WebKitDOMHTMLScriptElement
    {
        // DEBUG: WebKitDOMHTMLElement parent_instance
        [FieldOffset(0)]
        public _WebKitDOMHTMLElement parent_instance;
    }

    // DEBUG: struct _WebKitDOMHTMLScriptElementClass { WebKitDOMHTMLElementClass parent_class;}
    [StructLayout(LayoutKind.Explicit, Size = 68)]
    public unsafe struct _WebKitDOMHTMLScriptElementClass
    {
        // DEBUG: WebKitDOMHTMLElementClass parent_class
        [FieldOffset(0)]
        public _WebKitDOMHTMLElementClass parent_class;
    }

    public unsafe partial class WebKitDOMHTMLScriptElement: GLib.Object
    {
        public WebKitDOMHTMLScriptElement(IntPtr handle) : base(handle) { }
        // DEBUG: WEBKIT_API GTypewebkit_dom_html_script_element_get_type (void)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_script_element_get_type")]
        internal static extern uint webkit_dom_html_script_element_get_type();
        public GLib.GType Type
        {
            get
            {
                return new GLib.GType((IntPtr)webkit_dom_html_script_element_get_type());
            }
        }

        // DEBUG: WEBKIT_API gchar*webkit_dom_html_script_element_get_text(WebKitDOMHTMLScriptElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_script_element_get_text")]
        internal static extern sbyte* webkit_dom_html_script_element_get_text(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_script_element_set_text(WebKitDOMHTMLScriptElement* self, const gchar* value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_script_element_set_text")]
        internal static extern void webkit_dom_html_script_element_set_text(global::System.IntPtr self, global::System.IntPtr value);

        // DEBUG: WEBKIT_API gchar*webkit_dom_html_script_element_get_html_for(WebKitDOMHTMLScriptElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_script_element_get_html_for")]
        internal static extern sbyte* webkit_dom_html_script_element_get_html_for(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_script_element_set_html_for(WebKitDOMHTMLScriptElement* self, const gchar* value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_script_element_set_html_for")]
        internal static extern void webkit_dom_html_script_element_set_html_for(global::System.IntPtr self, global::System.IntPtr value);

        // DEBUG: WEBKIT_API gchar*webkit_dom_html_script_element_get_event(WebKitDOMHTMLScriptElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_script_element_get_event")]
        internal static extern sbyte* webkit_dom_html_script_element_get_event(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_script_element_set_event(WebKitDOMHTMLScriptElement* self, const gchar* value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_script_element_set_event")]
        internal static extern void webkit_dom_html_script_element_set_event(global::System.IntPtr self, global::System.IntPtr value);

        // DEBUG: WEBKIT_API gchar*webkit_dom_html_script_element_get_charset(WebKitDOMHTMLScriptElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_script_element_get_charset")]
        internal static extern sbyte* webkit_dom_html_script_element_get_charset(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_script_element_set_charset(WebKitDOMHTMLScriptElement* self, const gchar* value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_script_element_set_charset")]
        internal static extern void webkit_dom_html_script_element_set_charset(global::System.IntPtr self, global::System.IntPtr value);

        // DEBUG: WEBKIT_API gbooleanwebkit_dom_html_script_element_get_async(WebKitDOMHTMLScriptElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_script_element_get_async")]
        internal static extern int webkit_dom_html_script_element_get_async(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_script_element_set_async(WebKitDOMHTMLScriptElement* self, gboolean value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_script_element_set_async")]
        internal static extern void webkit_dom_html_script_element_set_async(global::System.IntPtr self, int value);

        // DEBUG: WEBKIT_API gbooleanwebkit_dom_html_script_element_get_defer(WebKitDOMHTMLScriptElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_script_element_get_defer")]
        internal static extern int webkit_dom_html_script_element_get_defer(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_script_element_set_defer(WebKitDOMHTMLScriptElement* self, gboolean value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_script_element_set_defer")]
        internal static extern void webkit_dom_html_script_element_set_defer(global::System.IntPtr self, int value);

        // DEBUG: WEBKIT_API gchar*webkit_dom_html_script_element_get_src(WebKitDOMHTMLScriptElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_script_element_get_src")]
        internal static extern sbyte* webkit_dom_html_script_element_get_src(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_script_element_set_src(WebKitDOMHTMLScriptElement* self, const gchar* value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_script_element_set_src")]
        internal static extern void webkit_dom_html_script_element_set_src(global::System.IntPtr self, global::System.IntPtr value);
    }
}
