//----------------------------------------------------------------------------
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
//----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace Webbed.Scripting.Interop
{
    // DEBUG: struct _WebKitDOMUIEvent { WebKitDOMEvent parent_instance;}
    [StructLayout(LayoutKind.Explicit, Size = 16)]
    public unsafe struct _WebKitDOMUIEvent
    {
        // DEBUG: WebKitDOMEvent parent_instance
        [FieldOffset(0)]
        public _WebKitDOMEvent parent_instance;
    }

    // DEBUG: struct _WebKitDOMUIEventClass { WebKitDOMEventClass parent_class;}
    [StructLayout(LayoutKind.Explicit, Size = 68)]
    public unsafe struct _WebKitDOMUIEventClass
    {
        // DEBUG: WebKitDOMEventClass parent_class
        [FieldOffset(0)]
        public _WebKitDOMEventClass parent_class;
    }

    public unsafe partial class WebKitDOMUIEvent: GLib.Object
    {
        public WebKitDOMUIEvent(IntPtr handle) : base(handle) { }
        // DEBUG: WEBKIT_API GTypewebkit_dom_ui_event_get_type (void)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_ui_event_get_type")]
        internal static extern uint webkit_dom_ui_event_get_type();
        public GLib.GType Type
        {
            get
            {
                return new GLib.GType((IntPtr)webkit_dom_ui_event_get_type());
            }
        }

        // DEBUG: WEBKIT_API voidwebkit_dom_ui_event_init_ui_event(WebKitDOMUIEvent* self, const gchar* type, gboolean can_bubble, gboolean cancelable, WebKitDOMDOMWindow* view, glong detail)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_ui_event_init_ui_event")]
        internal static extern void webkit_dom_ui_event_init_ui_event(global::System.IntPtr self, global::System.IntPtr type, int can_bubble, int cancelable, global::System.IntPtr view, int detail);

        // DEBUG: WEBKIT_API WebKitDOMDOMWindow*webkit_dom_ui_event_get_view(WebKitDOMUIEvent* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_ui_event_get_view")]
        internal static extern global::System.IntPtr webkit_dom_ui_event_get_view(global::System.IntPtr self);

        // DEBUG: WEBKIT_API glongwebkit_dom_ui_event_get_detail(WebKitDOMUIEvent* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_ui_event_get_detail")]
        internal static extern int webkit_dom_ui_event_get_detail(global::System.IntPtr self);

        // DEBUG: WEBKIT_API glongwebkit_dom_ui_event_get_key_code(WebKitDOMUIEvent* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_ui_event_get_key_code")]
        internal static extern int webkit_dom_ui_event_get_key_code(global::System.IntPtr self);

        // DEBUG: WEBKIT_API glongwebkit_dom_ui_event_get_char_code(WebKitDOMUIEvent* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_ui_event_get_char_code")]
        internal static extern int webkit_dom_ui_event_get_char_code(global::System.IntPtr self);

        // DEBUG: WEBKIT_API glongwebkit_dom_ui_event_get_layer_x(WebKitDOMUIEvent* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_ui_event_get_layer_x")]
        internal static extern int webkit_dom_ui_event_get_layer_x(global::System.IntPtr self);

        // DEBUG: WEBKIT_API glongwebkit_dom_ui_event_get_layer_y(WebKitDOMUIEvent* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_ui_event_get_layer_y")]
        internal static extern int webkit_dom_ui_event_get_layer_y(global::System.IntPtr self);

        // DEBUG: WEBKIT_API glongwebkit_dom_ui_event_get_page_x(WebKitDOMUIEvent* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_ui_event_get_page_x")]
        internal static extern int webkit_dom_ui_event_get_page_x(global::System.IntPtr self);

        // DEBUG: WEBKIT_API glongwebkit_dom_ui_event_get_page_y(WebKitDOMUIEvent* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_ui_event_get_page_y")]
        internal static extern int webkit_dom_ui_event_get_page_y(global::System.IntPtr self);

        // DEBUG: WEBKIT_API glongwebkit_dom_ui_event_get_which(WebKitDOMUIEvent* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_ui_event_get_which")]
        internal static extern int webkit_dom_ui_event_get_which(global::System.IntPtr self);
    }
}
