//----------------------------------------------------------------------------
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
//----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace Webbed.Scripting.Interop
{
    // DEBUG: struct _WebKitDOMHTMLTableSectionElement { WebKitDOMHTMLElement parent_instance;}
    [StructLayout(LayoutKind.Explicit, Size = 16)]
    public unsafe struct _WebKitDOMHTMLTableSectionElement
    {
        // DEBUG: WebKitDOMHTMLElement parent_instance
        [FieldOffset(0)]
        public _WebKitDOMHTMLElement parent_instance;
    }

    // DEBUG: struct _WebKitDOMHTMLTableSectionElementClass { WebKitDOMHTMLElementClass parent_class;}
    [StructLayout(LayoutKind.Explicit, Size = 68)]
    public unsafe struct _WebKitDOMHTMLTableSectionElementClass
    {
        // DEBUG: WebKitDOMHTMLElementClass parent_class
        [FieldOffset(0)]
        public _WebKitDOMHTMLElementClass parent_class;
    }

    public unsafe partial class WebKitDOMHTMLTableSectionElement: GLib.Object
    {
        public WebKitDOMHTMLTableSectionElement(IntPtr handle) : base(handle) { }
        // DEBUG: WEBKIT_API GTypewebkit_dom_html_table_section_element_get_type (void)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_table_section_element_get_type")]
        internal static extern uint webkit_dom_html_table_section_element_get_type();
        public GLib.GType Type
        {
            get
            {
                return new GLib.GType((IntPtr)webkit_dom_html_table_section_element_get_type());
            }
        }

        // DEBUG: WEBKIT_API WebKitDOMHTMLElement*webkit_dom_html_table_section_element_insert_row(WebKitDOMHTMLTableSectionElement* self, glong index, GError **error)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_table_section_element_insert_row")]
        internal static extern global::System.IntPtr webkit_dom_html_table_section_element_insert_row(global::System.IntPtr self, int index, global::System.IntPtr error);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_table_section_element_delete_row(WebKitDOMHTMLTableSectionElement* self, glong index, GError **error)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_table_section_element_delete_row")]
        internal static extern void webkit_dom_html_table_section_element_delete_row(global::System.IntPtr self, int index, global::System.IntPtr error);

        // DEBUG: WEBKIT_API gchar*webkit_dom_html_table_section_element_get_align(WebKitDOMHTMLTableSectionElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_table_section_element_get_align")]
        internal static extern sbyte* webkit_dom_html_table_section_element_get_align(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_table_section_element_set_align(WebKitDOMHTMLTableSectionElement* self, const gchar* value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_table_section_element_set_align")]
        internal static extern void webkit_dom_html_table_section_element_set_align(global::System.IntPtr self, global::System.IntPtr value);

        // DEBUG: WEBKIT_API gchar*webkit_dom_html_table_section_element_get_ch(WebKitDOMHTMLTableSectionElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_table_section_element_get_ch")]
        internal static extern sbyte* webkit_dom_html_table_section_element_get_ch(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_table_section_element_set_ch(WebKitDOMHTMLTableSectionElement* self, const gchar* value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_table_section_element_set_ch")]
        internal static extern void webkit_dom_html_table_section_element_set_ch(global::System.IntPtr self, global::System.IntPtr value);

        // DEBUG: WEBKIT_API gchar*webkit_dom_html_table_section_element_get_ch_off(WebKitDOMHTMLTableSectionElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_table_section_element_get_ch_off")]
        internal static extern sbyte* webkit_dom_html_table_section_element_get_ch_off(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_table_section_element_set_ch_off(WebKitDOMHTMLTableSectionElement* self, const gchar* value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_table_section_element_set_ch_off")]
        internal static extern void webkit_dom_html_table_section_element_set_ch_off(global::System.IntPtr self, global::System.IntPtr value);

        // DEBUG: WEBKIT_API gchar*webkit_dom_html_table_section_element_get_v_align(WebKitDOMHTMLTableSectionElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_table_section_element_get_v_align")]
        internal static extern sbyte* webkit_dom_html_table_section_element_get_v_align(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_table_section_element_set_v_align(WebKitDOMHTMLTableSectionElement* self, const gchar* value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_table_section_element_set_v_align")]
        internal static extern void webkit_dom_html_table_section_element_set_v_align(global::System.IntPtr self, global::System.IntPtr value);

        // DEBUG: WEBKIT_API WebKitDOMHTMLCollection*webkit_dom_html_table_section_element_get_rows(WebKitDOMHTMLTableSectionElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_table_section_element_get_rows")]
        internal static extern global::System.IntPtr webkit_dom_html_table_section_element_get_rows(global::System.IntPtr self);
    }
}
