//----------------------------------------------------------------------------
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
//----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace Webbed.Scripting.Interop
{
    // DEBUG: struct _WebKitDOMHTMLHRElement { WebKitDOMHTMLElement parent_instance;}
    [StructLayout(LayoutKind.Explicit, Size = 16)]
    public unsafe struct _WebKitDOMHTMLHRElement
    {
        // DEBUG: WebKitDOMHTMLElement parent_instance
        [FieldOffset(0)]
        public _WebKitDOMHTMLElement parent_instance;
    }

    // DEBUG: struct _WebKitDOMHTMLHRElementClass { WebKitDOMHTMLElementClass parent_class;}
    [StructLayout(LayoutKind.Explicit, Size = 68)]
    public unsafe struct _WebKitDOMHTMLHRElementClass
    {
        // DEBUG: WebKitDOMHTMLElementClass parent_class
        [FieldOffset(0)]
        public _WebKitDOMHTMLElementClass parent_class;
    }

    public unsafe partial class WebKitDOMHTMLHRElement: GLib.Object
    {
        public WebKitDOMHTMLHRElement(IntPtr handle) : base(handle) { }
        // DEBUG: WEBKIT_API GTypewebkit_dom_htmlhr_element_get_type (void)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_htmlhr_element_get_type")]
        internal static extern uint webkit_dom_htmlhr_element_get_type();
        public GLib.GType Type
        {
            get
            {
                return new GLib.GType((IntPtr)webkit_dom_htmlhr_element_get_type());
            }
        }

        // DEBUG: WEBKIT_API gchar*webkit_dom_htmlhr_element_get_align(WebKitDOMHTMLHRElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_htmlhr_element_get_align")]
        internal static extern sbyte* webkit_dom_htmlhr_element_get_align(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_htmlhr_element_set_align(WebKitDOMHTMLHRElement* self, const gchar* value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_htmlhr_element_set_align")]
        internal static extern void webkit_dom_htmlhr_element_set_align(global::System.IntPtr self, global::System.IntPtr value);

        // DEBUG: WEBKIT_API gbooleanwebkit_dom_htmlhr_element_get_no_shade(WebKitDOMHTMLHRElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_htmlhr_element_get_no_shade")]
        internal static extern int webkit_dom_htmlhr_element_get_no_shade(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_htmlhr_element_set_no_shade(WebKitDOMHTMLHRElement* self, gboolean value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_htmlhr_element_set_no_shade")]
        internal static extern void webkit_dom_htmlhr_element_set_no_shade(global::System.IntPtr self, int value);

        // DEBUG: WEBKIT_API gchar*webkit_dom_htmlhr_element_get_size(WebKitDOMHTMLHRElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_htmlhr_element_get_size")]
        internal static extern sbyte* webkit_dom_htmlhr_element_get_size(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_htmlhr_element_set_size(WebKitDOMHTMLHRElement* self, const gchar* value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_htmlhr_element_set_size")]
        internal static extern void webkit_dom_htmlhr_element_set_size(global::System.IntPtr self, global::System.IntPtr value);

        // DEBUG: WEBKIT_API gchar*webkit_dom_htmlhr_element_get_width(WebKitDOMHTMLHRElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_htmlhr_element_get_width")]
        internal static extern sbyte* webkit_dom_htmlhr_element_get_width(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_htmlhr_element_set_width(WebKitDOMHTMLHRElement* self, const gchar* value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_htmlhr_element_set_width")]
        internal static extern void webkit_dom_htmlhr_element_set_width(global::System.IntPtr self, global::System.IntPtr value);
    }
}
