//----------------------------------------------------------------------------
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
//----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace Webbed.Scripting.Interop
{
    // DEBUG: struct _WebKitDOMTimeRanges { WebKitDOMObject parent_instance;}
    [StructLayout(LayoutKind.Explicit, Size = 16)]
    public unsafe struct _WebKitDOMTimeRanges
    {
        // DEBUG: WebKitDOMObject parent_instance
        [FieldOffset(0)]
        public _WebKitDOMObject parent_instance;
    }

    // DEBUG: struct _WebKitDOMTimeRangesClass { WebKitDOMObjectClass parent_class;}
    [StructLayout(LayoutKind.Explicit, Size = 68)]
    public unsafe struct _WebKitDOMTimeRangesClass
    {
        // DEBUG: WebKitDOMObjectClass parent_class
        [FieldOffset(0)]
        public _WebKitDOMObjectClass parent_class;
    }

    public unsafe partial class WebKitDOMTimeRanges: GLib.Object
    {
        public WebKitDOMTimeRanges(IntPtr handle) : base(handle) { }
        // DEBUG: WEBKIT_API GTypewebkit_dom_time_ranges_get_type (void)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_time_ranges_get_type")]
        internal static extern uint webkit_dom_time_ranges_get_type();
        public GLib.GType Type
        {
            get
            {
                return new GLib.GType((IntPtr)webkit_dom_time_ranges_get_type());
            }
        }

        // DEBUG: WEBKIT_API gfloatwebkit_dom_time_ranges_start(WebKitDOMTimeRanges* self, gulong index, GError **error)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_time_ranges_start")]
        internal static extern float webkit_dom_time_ranges_start(global::System.IntPtr self, uint index, global::System.IntPtr error);

        // DEBUG: WEBKIT_API gfloatwebkit_dom_time_ranges_end(WebKitDOMTimeRanges* self, gulong index, GError **error)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_time_ranges_end")]
        internal static extern float webkit_dom_time_ranges_end(global::System.IntPtr self, uint index, global::System.IntPtr error);

        // DEBUG: WEBKIT_API gulongwebkit_dom_time_ranges_get_length(WebKitDOMTimeRanges* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_time_ranges_get_length")]
        internal static extern uint webkit_dom_time_ranges_get_length(global::System.IntPtr self);
    }
}
