//----------------------------------------------------------------------------
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
//----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace Webbed.Scripting.Interop
{
    // DEBUG: struct _WebKitDOMMouseEvent { WebKitDOMUIEvent parent_instance;}
    [StructLayout(LayoutKind.Explicit, Size = 16)]
    public unsafe struct _WebKitDOMMouseEvent
    {
        // DEBUG: WebKitDOMUIEvent parent_instance
        [FieldOffset(0)]
        public _WebKitDOMUIEvent parent_instance;
    }

    // DEBUG: struct _WebKitDOMMouseEventClass { WebKitDOMUIEventClass parent_class;}
    [StructLayout(LayoutKind.Explicit, Size = 68)]
    public unsafe struct _WebKitDOMMouseEventClass
    {
        // DEBUG: WebKitDOMUIEventClass parent_class
        [FieldOffset(0)]
        public _WebKitDOMUIEventClass parent_class;
    }

    public unsafe partial class WebKitDOMMouseEvent: GLib.Object
    {
        public WebKitDOMMouseEvent(IntPtr handle) : base(handle) { }
        // DEBUG: WEBKIT_API GTypewebkit_dom_mouse_event_get_type (void)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_mouse_event_get_type")]
        internal static extern uint webkit_dom_mouse_event_get_type();
        public GLib.GType Type
        {
            get
            {
                return new GLib.GType((IntPtr)webkit_dom_mouse_event_get_type());
            }
        }

        // DEBUG: WEBKIT_API voidwebkit_dom_mouse_event_init_mouse_event(WebKitDOMMouseEvent* self, const gchar* type, gboolean can_bubble, gboolean cancelable, WebKitDOMDOMWindow* view, glong detail, glong screen_x, glong screen_y, glong client_x, glong client_y, gboolean ctrl_key, gboolean alt_key, gboolean shift_key, gboolean meta_key, gushort button, WebKitDOMEventTarget* related_target)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_mouse_event_init_mouse_event")]
        internal static extern void webkit_dom_mouse_event_init_mouse_event(global::System.IntPtr self, global::System.IntPtr type, int can_bubble, int cancelable, global::System.IntPtr view, int detail, int screen_x, int screen_y, int client_x, int client_y, int ctrl_key, int alt_key, int shift_key, int meta_key, ushort button, global::System.IntPtr related_target);

        // DEBUG: WEBKIT_API glongwebkit_dom_mouse_event_get_screen_x(WebKitDOMMouseEvent* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_mouse_event_get_screen_x")]
        internal static extern int webkit_dom_mouse_event_get_screen_x(global::System.IntPtr self);

        // DEBUG: WEBKIT_API glongwebkit_dom_mouse_event_get_screen_y(WebKitDOMMouseEvent* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_mouse_event_get_screen_y")]
        internal static extern int webkit_dom_mouse_event_get_screen_y(global::System.IntPtr self);

        // DEBUG: WEBKIT_API glongwebkit_dom_mouse_event_get_client_x(WebKitDOMMouseEvent* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_mouse_event_get_client_x")]
        internal static extern int webkit_dom_mouse_event_get_client_x(global::System.IntPtr self);

        // DEBUG: WEBKIT_API glongwebkit_dom_mouse_event_get_client_y(WebKitDOMMouseEvent* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_mouse_event_get_client_y")]
        internal static extern int webkit_dom_mouse_event_get_client_y(global::System.IntPtr self);

        // DEBUG: WEBKIT_API glongwebkit_dom_mouse_event_get_webkit_movement_x(WebKitDOMMouseEvent* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_mouse_event_get_webkit_movement_x")]
        internal static extern int webkit_dom_mouse_event_get_webkit_movement_x(global::System.IntPtr self);

        // DEBUG: WEBKIT_API glongwebkit_dom_mouse_event_get_webkit_movement_y(WebKitDOMMouseEvent* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_mouse_event_get_webkit_movement_y")]
        internal static extern int webkit_dom_mouse_event_get_webkit_movement_y(global::System.IntPtr self);

        // DEBUG: WEBKIT_API gbooleanwebkit_dom_mouse_event_get_ctrl_key(WebKitDOMMouseEvent* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_mouse_event_get_ctrl_key")]
        internal static extern int webkit_dom_mouse_event_get_ctrl_key(global::System.IntPtr self);

        // DEBUG: WEBKIT_API gbooleanwebkit_dom_mouse_event_get_shift_key(WebKitDOMMouseEvent* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_mouse_event_get_shift_key")]
        internal static extern int webkit_dom_mouse_event_get_shift_key(global::System.IntPtr self);

        // DEBUG: WEBKIT_API gbooleanwebkit_dom_mouse_event_get_alt_key(WebKitDOMMouseEvent* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_mouse_event_get_alt_key")]
        internal static extern int webkit_dom_mouse_event_get_alt_key(global::System.IntPtr self);

        // DEBUG: WEBKIT_API gbooleanwebkit_dom_mouse_event_get_meta_key(WebKitDOMMouseEvent* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_mouse_event_get_meta_key")]
        internal static extern int webkit_dom_mouse_event_get_meta_key(global::System.IntPtr self);

        // DEBUG: WEBKIT_API gushortwebkit_dom_mouse_event_get_button(WebKitDOMMouseEvent* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_mouse_event_get_button")]
        internal static extern ushort webkit_dom_mouse_event_get_button(global::System.IntPtr self);

        // DEBUG: WEBKIT_API WebKitDOMEventTarget*webkit_dom_mouse_event_get_related_target(WebKitDOMMouseEvent* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_mouse_event_get_related_target")]
        internal static extern global::System.IntPtr webkit_dom_mouse_event_get_related_target(global::System.IntPtr self);

        // DEBUG: WEBKIT_API glongwebkit_dom_mouse_event_get_offset_x(WebKitDOMMouseEvent* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_mouse_event_get_offset_x")]
        internal static extern int webkit_dom_mouse_event_get_offset_x(global::System.IntPtr self);

        // DEBUG: WEBKIT_API glongwebkit_dom_mouse_event_get_offset_y(WebKitDOMMouseEvent* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_mouse_event_get_offset_y")]
        internal static extern int webkit_dom_mouse_event_get_offset_y(global::System.IntPtr self);

        // DEBUG: WEBKIT_API glongwebkit_dom_mouse_event_get_x(WebKitDOMMouseEvent* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_mouse_event_get_x")]
        internal static extern int webkit_dom_mouse_event_get_x(global::System.IntPtr self);

        // DEBUG: WEBKIT_API glongwebkit_dom_mouse_event_get_y(WebKitDOMMouseEvent* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_mouse_event_get_y")]
        internal static extern int webkit_dom_mouse_event_get_y(global::System.IntPtr self);

        // DEBUG: WEBKIT_API WebKitDOMNode*webkit_dom_mouse_event_get_from_element(WebKitDOMMouseEvent* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_mouse_event_get_from_element")]
        internal static extern global::System.IntPtr webkit_dom_mouse_event_get_from_element(global::System.IntPtr self);

        // DEBUG: WEBKIT_API WebKitDOMNode*webkit_dom_mouse_event_get_to_element(WebKitDOMMouseEvent* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_mouse_event_get_to_element")]
        internal static extern global::System.IntPtr webkit_dom_mouse_event_get_to_element(global::System.IntPtr self);
    }
}
