//----------------------------------------------------------------------------
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
//----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace Webbed.Scripting.Interop
{
    // DEBUG: struct _WebKitDOMHTMLAreaElement { WebKitDOMHTMLElement parent_instance;}
    [StructLayout(LayoutKind.Explicit, Size = 16)]
    public unsafe struct _WebKitDOMHTMLAreaElement
    {
        // DEBUG: WebKitDOMHTMLElement parent_instance
        [FieldOffset(0)]
        public _WebKitDOMHTMLElement parent_instance;
    }

    // DEBUG: struct _WebKitDOMHTMLAreaElementClass { WebKitDOMHTMLElementClass parent_class;}
    [StructLayout(LayoutKind.Explicit, Size = 68)]
    public unsafe struct _WebKitDOMHTMLAreaElementClass
    {
        // DEBUG: WebKitDOMHTMLElementClass parent_class
        [FieldOffset(0)]
        public _WebKitDOMHTMLElementClass parent_class;
    }

    public unsafe partial class WebKitDOMHTMLAreaElement: GLib.Object
    {
        public WebKitDOMHTMLAreaElement(IntPtr handle) : base(handle) { }
        // DEBUG: WEBKIT_API GTypewebkit_dom_html_area_element_get_type (void)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_area_element_get_type")]
        internal static extern uint webkit_dom_html_area_element_get_type();
        public GLib.GType Type
        {
            get
            {
                return new GLib.GType((IntPtr)webkit_dom_html_area_element_get_type());
            }
        }

        // DEBUG: WEBKIT_API gchar*webkit_dom_html_area_element_get_alt(WebKitDOMHTMLAreaElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_area_element_get_alt")]
        internal static extern sbyte* webkit_dom_html_area_element_get_alt(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_area_element_set_alt(WebKitDOMHTMLAreaElement* self, const gchar* value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_area_element_set_alt")]
        internal static extern void webkit_dom_html_area_element_set_alt(global::System.IntPtr self, global::System.IntPtr value);

        // DEBUG: WEBKIT_API gchar*webkit_dom_html_area_element_get_coords(WebKitDOMHTMLAreaElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_area_element_get_coords")]
        internal static extern sbyte* webkit_dom_html_area_element_get_coords(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_area_element_set_coords(WebKitDOMHTMLAreaElement* self, const gchar* value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_area_element_set_coords")]
        internal static extern void webkit_dom_html_area_element_set_coords(global::System.IntPtr self, global::System.IntPtr value);

        // DEBUG: WEBKIT_API gchar*webkit_dom_html_area_element_get_href(WebKitDOMHTMLAreaElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_area_element_get_href")]
        internal static extern sbyte* webkit_dom_html_area_element_get_href(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_area_element_set_href(WebKitDOMHTMLAreaElement* self, const gchar* value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_area_element_set_href")]
        internal static extern void webkit_dom_html_area_element_set_href(global::System.IntPtr self, global::System.IntPtr value);

        // DEBUG: WEBKIT_API gbooleanwebkit_dom_html_area_element_get_no_href(WebKitDOMHTMLAreaElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_area_element_get_no_href")]
        internal static extern int webkit_dom_html_area_element_get_no_href(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_area_element_set_no_href(WebKitDOMHTMLAreaElement* self, gboolean value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_area_element_set_no_href")]
        internal static extern void webkit_dom_html_area_element_set_no_href(global::System.IntPtr self, int value);

        // DEBUG: WEBKIT_API gchar*webkit_dom_html_area_element_get_ping(WebKitDOMHTMLAreaElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_area_element_get_ping")]
        internal static extern sbyte* webkit_dom_html_area_element_get_ping(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_area_element_set_ping(WebKitDOMHTMLAreaElement* self, const gchar* value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_area_element_set_ping")]
        internal static extern void webkit_dom_html_area_element_set_ping(global::System.IntPtr self, global::System.IntPtr value);

        // DEBUG: WEBKIT_API gchar*webkit_dom_html_area_element_get_shape(WebKitDOMHTMLAreaElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_area_element_get_shape")]
        internal static extern sbyte* webkit_dom_html_area_element_get_shape(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_area_element_set_shape(WebKitDOMHTMLAreaElement* self, const gchar* value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_area_element_set_shape")]
        internal static extern void webkit_dom_html_area_element_set_shape(global::System.IntPtr self, global::System.IntPtr value);

        // DEBUG: WEBKIT_API gchar*webkit_dom_html_area_element_get_target(WebKitDOMHTMLAreaElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_area_element_get_target")]
        internal static extern sbyte* webkit_dom_html_area_element_get_target(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_area_element_set_target(WebKitDOMHTMLAreaElement* self, const gchar* value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_area_element_set_target")]
        internal static extern void webkit_dom_html_area_element_set_target(global::System.IntPtr self, global::System.IntPtr value);

        // DEBUG: WEBKIT_API gchar*webkit_dom_html_area_element_get_hash(WebKitDOMHTMLAreaElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_area_element_get_hash")]
        internal static extern sbyte* webkit_dom_html_area_element_get_hash(global::System.IntPtr self);

        // DEBUG: WEBKIT_API gchar*webkit_dom_html_area_element_get_host(WebKitDOMHTMLAreaElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_area_element_get_host")]
        internal static extern sbyte* webkit_dom_html_area_element_get_host(global::System.IntPtr self);

        // DEBUG: WEBKIT_API gchar*webkit_dom_html_area_element_get_hostname(WebKitDOMHTMLAreaElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_area_element_get_hostname")]
        internal static extern sbyte* webkit_dom_html_area_element_get_hostname(global::System.IntPtr self);

        // DEBUG: WEBKIT_API gchar*webkit_dom_html_area_element_get_pathname(WebKitDOMHTMLAreaElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_area_element_get_pathname")]
        internal static extern sbyte* webkit_dom_html_area_element_get_pathname(global::System.IntPtr self);

        // DEBUG: WEBKIT_API gchar*webkit_dom_html_area_element_get_port(WebKitDOMHTMLAreaElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_area_element_get_port")]
        internal static extern sbyte* webkit_dom_html_area_element_get_port(global::System.IntPtr self);

        // DEBUG: WEBKIT_API gchar*webkit_dom_html_area_element_get_protocol(WebKitDOMHTMLAreaElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_area_element_get_protocol")]
        internal static extern sbyte* webkit_dom_html_area_element_get_protocol(global::System.IntPtr self);

        // DEBUG: WEBKIT_API gchar*webkit_dom_html_area_element_get_search(WebKitDOMHTMLAreaElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_area_element_get_search")]
        internal static extern sbyte* webkit_dom_html_area_element_get_search(global::System.IntPtr self);
    }
}
