//----------------------------------------------------------------------------
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
//----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace Webbed.Scripting.Interop
{
    // DEBUG: struct _WebKitDOMScreen { WebKitDOMObject parent_instance;}
    [StructLayout(LayoutKind.Explicit, Size = 16)]
    public unsafe struct _WebKitDOMScreen
    {
        // DEBUG: WebKitDOMObject parent_instance
        [FieldOffset(0)]
        public _WebKitDOMObject parent_instance;
    }

    // DEBUG: struct _WebKitDOMScreenClass { WebKitDOMObjectClass parent_class;}
    [StructLayout(LayoutKind.Explicit, Size = 68)]
    public unsafe struct _WebKitDOMScreenClass
    {
        // DEBUG: WebKitDOMObjectClass parent_class
        [FieldOffset(0)]
        public _WebKitDOMObjectClass parent_class;
    }

    public unsafe partial class WebKitDOMScreen: GLib.Object
    {
        public WebKitDOMScreen(IntPtr handle) : base(handle) { }
        // DEBUG: WEBKIT_API GTypewebkit_dom_screen_get_type (void)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_screen_get_type")]
        internal static extern uint webkit_dom_screen_get_type();
        public GLib.GType Type
        {
            get
            {
                return new GLib.GType((IntPtr)webkit_dom_screen_get_type());
            }
        }

        // DEBUG: WEBKIT_API gulongwebkit_dom_screen_get_height(WebKitDOMScreen* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_screen_get_height")]
        internal static extern uint webkit_dom_screen_get_height(global::System.IntPtr self);

        // DEBUG: WEBKIT_API gulongwebkit_dom_screen_get_width(WebKitDOMScreen* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_screen_get_width")]
        internal static extern uint webkit_dom_screen_get_width(global::System.IntPtr self);

        // DEBUG: WEBKIT_API gulongwebkit_dom_screen_get_color_depth(WebKitDOMScreen* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_screen_get_color_depth")]
        internal static extern uint webkit_dom_screen_get_color_depth(global::System.IntPtr self);

        // DEBUG: WEBKIT_API gulongwebkit_dom_screen_get_pixel_depth(WebKitDOMScreen* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_screen_get_pixel_depth")]
        internal static extern uint webkit_dom_screen_get_pixel_depth(global::System.IntPtr self);

        // DEBUG: WEBKIT_API glongwebkit_dom_screen_get_avail_left(WebKitDOMScreen* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_screen_get_avail_left")]
        internal static extern int webkit_dom_screen_get_avail_left(global::System.IntPtr self);

        // DEBUG: WEBKIT_API glongwebkit_dom_screen_get_avail_top(WebKitDOMScreen* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_screen_get_avail_top")]
        internal static extern int webkit_dom_screen_get_avail_top(global::System.IntPtr self);

        // DEBUG: WEBKIT_API gulongwebkit_dom_screen_get_avail_height(WebKitDOMScreen* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_screen_get_avail_height")]
        internal static extern uint webkit_dom_screen_get_avail_height(global::System.IntPtr self);

        // DEBUG: WEBKIT_API gulongwebkit_dom_screen_get_avail_width(WebKitDOMScreen* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_screen_get_avail_width")]
        internal static extern uint webkit_dom_screen_get_avail_width(global::System.IntPtr self);
    }
}
