//----------------------------------------------------------------------------
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
//----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace Webbed.Scripting.Interop
{
    // DEBUG: struct _WebKitDOMElement { WebKitDOMNode parent_instance;}
    [StructLayout(LayoutKind.Explicit, Size = 16)]
    public unsafe struct _WebKitDOMElement
    {
        // DEBUG: WebKitDOMNode parent_instance
        [FieldOffset(0)]
        public _WebKitDOMNode parent_instance;
    }

    // DEBUG: struct _WebKitDOMElementClass { WebKitDOMNodeClass parent_class;}
    [StructLayout(LayoutKind.Explicit, Size = 68)]
    public unsafe struct _WebKitDOMElementClass
    {
        // DEBUG: WebKitDOMNodeClass parent_class
        [FieldOffset(0)]
        public _WebKitDOMNodeClass parent_class;
    }

    public unsafe partial class WebKitDOMElement :GLib.Object
    {
        public WebKitDOMElement(IntPtr handle) : base(handle) { }
        // DEBUG: WEBKIT_API GTypewebkit_dom_element_get_type (void)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_element_get_type")]
        internal static extern uint webkit_dom_element_get_type();

        public GLib.GType Type
        {
            get
            {
                return new GLib.GType((IntPtr)webkit_dom_element_get_type());
            }
        }

        // DEBUG: WEBKIT_API gchar*webkit_dom_element_get_attribute(WebKitDOMElement* self, const gchar* name)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_element_get_attribute")]
        internal static extern sbyte* webkit_dom_element_get_attribute(global::System.IntPtr self, global::System.IntPtr name);

        // DEBUG: WEBKIT_API voidwebkit_dom_element_set_attribute(WebKitDOMElement* self, const gchar* name, const gchar* value, GError **error)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_element_set_attribute")]
        internal static extern void webkit_dom_element_set_attribute(global::System.IntPtr self, global::System.IntPtr name, global::System.IntPtr value, global::System.IntPtr error);

        // DEBUG: WEBKIT_API voidwebkit_dom_element_remove_attribute(WebKitDOMElement* self, const gchar* name)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_element_remove_attribute")]
        internal static extern void webkit_dom_element_remove_attribute(global::System.IntPtr self, global::System.IntPtr name);

        // DEBUG: WEBKIT_API WebKitDOMAttr*webkit_dom_element_get_attribute_node(WebKitDOMElement* self, const gchar* name)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_element_get_attribute_node")]
        internal static extern global::System.IntPtr webkit_dom_element_get_attribute_node(global::System.IntPtr self, global::System.IntPtr name);

        // DEBUG: WEBKIT_API WebKitDOMAttr*webkit_dom_element_set_attribute_node(WebKitDOMElement* self, WebKitDOMAttr* new_attr, GError **error)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_element_set_attribute_node")]
        internal static extern global::System.IntPtr webkit_dom_element_set_attribute_node(global::System.IntPtr self, global::System.IntPtr new_attr, global::System.IntPtr error);

        // DEBUG: WEBKIT_API WebKitDOMAttr*webkit_dom_element_remove_attribute_node(WebKitDOMElement* self, WebKitDOMAttr* old_attr, GError **error)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_element_remove_attribute_node")]
        internal static extern global::System.IntPtr webkit_dom_element_remove_attribute_node(global::System.IntPtr self, global::System.IntPtr old_attr, global::System.IntPtr error);

        // DEBUG: WEBKIT_API WebKitDOMNodeList*webkit_dom_element_get_elements_by_tag_name(WebKitDOMElement* self, const gchar* name)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_element_get_elements_by_tag_name")]
        internal static extern global::System.IntPtr webkit_dom_element_get_elements_by_tag_name(global::System.IntPtr self, global::System.IntPtr name);

        // DEBUG: WEBKIT_API gchar*webkit_dom_element_get_attribute_ns(WebKitDOMElement* self, const gchar* namespace_uri, const gchar* local_name)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_element_get_attribute_ns")]
        internal static extern sbyte* webkit_dom_element_get_attribute_ns(global::System.IntPtr self, global::System.IntPtr namespace_uri, global::System.IntPtr local_name);

        // DEBUG: WEBKIT_API voidwebkit_dom_element_set_attribute_ns(WebKitDOMElement* self, const gchar* namespace_uri, const gchar* qualified_name, const gchar* value, GError **error)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_element_set_attribute_ns")]
        internal static extern void webkit_dom_element_set_attribute_ns(global::System.IntPtr self, global::System.IntPtr namespace_uri, global::System.IntPtr qualified_name, global::System.IntPtr value, global::System.IntPtr error);

        // DEBUG: WEBKIT_API voidwebkit_dom_element_remove_attribute_ns(WebKitDOMElement* self, const gchar* namespace_uri, const gchar* local_name)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_element_remove_attribute_ns")]
        internal static extern void webkit_dom_element_remove_attribute_ns(global::System.IntPtr self, global::System.IntPtr namespace_uri, global::System.IntPtr local_name);

        // DEBUG: WEBKIT_API WebKitDOMNodeList*webkit_dom_element_get_elements_by_tag_name_ns(WebKitDOMElement* self, const gchar* namespace_uri, const gchar* local_name)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_element_get_elements_by_tag_name_ns")]
        internal static extern global::System.IntPtr webkit_dom_element_get_elements_by_tag_name_ns(global::System.IntPtr self, global::System.IntPtr namespace_uri, global::System.IntPtr local_name);

        // DEBUG: WEBKIT_API WebKitDOMAttr*webkit_dom_element_get_attribute_node_ns(WebKitDOMElement* self, const gchar* namespace_uri, const gchar* local_name)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_element_get_attribute_node_ns")]
        internal static extern global::System.IntPtr webkit_dom_element_get_attribute_node_ns(global::System.IntPtr self, global::System.IntPtr namespace_uri, global::System.IntPtr local_name);

        // DEBUG: WEBKIT_API WebKitDOMAttr*webkit_dom_element_set_attribute_node_ns(WebKitDOMElement* self, WebKitDOMAttr* new_attr, GError **error)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_element_set_attribute_node_ns")]
        internal static extern global::System.IntPtr webkit_dom_element_set_attribute_node_ns(global::System.IntPtr self, global::System.IntPtr new_attr, global::System.IntPtr error);

        // DEBUG: WEBKIT_API gbooleanwebkit_dom_element_has_attribute(WebKitDOMElement* self, const gchar* name)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_element_has_attribute")]
        internal static extern int webkit_dom_element_has_attribute(global::System.IntPtr self, global::System.IntPtr name);

        // DEBUG: WEBKIT_API gbooleanwebkit_dom_element_has_attribute_ns(WebKitDOMElement* self, const gchar* namespace_uri, const gchar* local_name)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_element_has_attribute_ns")]
        internal static extern int webkit_dom_element_has_attribute_ns(global::System.IntPtr self, global::System.IntPtr namespace_uri, global::System.IntPtr local_name);

        // DEBUG: WEBKIT_API voidwebkit_dom_element_focus(WebKitDOMElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_element_focus")]
        internal static extern void webkit_dom_element_focus(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_element_blur(WebKitDOMElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_element_blur")]
        internal static extern void webkit_dom_element_blur(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_element_scroll_into_view(WebKitDOMElement* self, gboolean align_with_top)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_element_scroll_into_view")]
        internal static extern void webkit_dom_element_scroll_into_view(global::System.IntPtr self, int align_with_top);

        // DEBUG: WEBKIT_API voidwebkit_dom_element_scroll_into_view_if_needed(WebKitDOMElement* self, gboolean center_if_needed)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_element_scroll_into_view_if_needed")]
        internal static extern void webkit_dom_element_scroll_into_view_if_needed(global::System.IntPtr self, int center_if_needed);

        // DEBUG: WEBKIT_API voidwebkit_dom_element_scroll_by_lines(WebKitDOMElement* self, glong lines)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_element_scroll_by_lines")]
        internal static extern void webkit_dom_element_scroll_by_lines(global::System.IntPtr self, int lines);

        // DEBUG: WEBKIT_API voidwebkit_dom_element_scroll_by_pages(WebKitDOMElement* self, glong pages)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_element_scroll_by_pages")]
        internal static extern void webkit_dom_element_scroll_by_pages(global::System.IntPtr self, int pages);

        // DEBUG: WEBKIT_API WebKitDOMNodeList*webkit_dom_element_get_elements_by_class_name(WebKitDOMElement* self, const gchar* name)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_element_get_elements_by_class_name")]
        internal static extern global::System.IntPtr webkit_dom_element_get_elements_by_class_name(global::System.IntPtr self, global::System.IntPtr name);

        // DEBUG: WEBKIT_API WebKitDOMElement*webkit_dom_element_query_selector(WebKitDOMElement* self, const gchar* selectors, GError **error)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_element_query_selector")]
        internal static extern global::System.IntPtr webkit_dom_element_query_selector(global::System.IntPtr self, global::System.IntPtr selectors, global::System.IntPtr error);

        // DEBUG: WEBKIT_API WebKitDOMNodeList*webkit_dom_element_query_selector_all(WebKitDOMElement* self, const gchar* selectors, GError **error)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_element_query_selector_all")]
        internal static extern global::System.IntPtr webkit_dom_element_query_selector_all(global::System.IntPtr self, global::System.IntPtr selectors, global::System.IntPtr error);

        // DEBUG: WEBKIT_API gbooleanwebkit_dom_element_webkit_matches_selector(WebKitDOMElement* self, const gchar* selectors, GError **error)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_element_webkit_matches_selector")]
        internal static extern int webkit_dom_element_webkit_matches_selector(global::System.IntPtr self, global::System.IntPtr selectors, global::System.IntPtr error);

        // DEBUG: WEBKIT_API voidwebkit_dom_element_webkit_request_full_screen(WebKitDOMElement* self, gushort flags)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_element_webkit_request_full_screen")]
        internal static extern void webkit_dom_element_webkit_request_full_screen(global::System.IntPtr self, ushort flags);

        // DEBUG: WEBKIT_API gchar*webkit_dom_element_get_tag_name(WebKitDOMElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_element_get_tag_name")]
        internal static extern sbyte* webkit_dom_element_get_tag_name(global::System.IntPtr self);

        // DEBUG: WEBKIT_API WebKitDOMCSSStyleDeclaration*webkit_dom_element_get_style(WebKitDOMElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_element_get_style")]
        internal static extern global::System.IntPtr webkit_dom_element_get_style(global::System.IntPtr self);

        // DEBUG: WEBKIT_API glongwebkit_dom_element_get_offset_left(WebKitDOMElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_element_get_offset_left")]
        internal static extern int webkit_dom_element_get_offset_left(global::System.IntPtr self);

        // DEBUG: WEBKIT_API glongwebkit_dom_element_get_offset_top(WebKitDOMElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_element_get_offset_top")]
        internal static extern int webkit_dom_element_get_offset_top(global::System.IntPtr self);

        // DEBUG: WEBKIT_API glongwebkit_dom_element_get_offset_width(WebKitDOMElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_element_get_offset_width")]
        internal static extern int webkit_dom_element_get_offset_width(global::System.IntPtr self);

        // DEBUG: WEBKIT_API glongwebkit_dom_element_get_offset_height(WebKitDOMElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_element_get_offset_height")]
        internal static extern int webkit_dom_element_get_offset_height(global::System.IntPtr self);

        // DEBUG: WEBKIT_API WebKitDOMElement*webkit_dom_element_get_offset_parent(WebKitDOMElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_element_get_offset_parent")]
        internal static extern global::System.IntPtr webkit_dom_element_get_offset_parent(global::System.IntPtr self);

        // DEBUG: WEBKIT_API glongwebkit_dom_element_get_client_left(WebKitDOMElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_element_get_client_left")]
        internal static extern int webkit_dom_element_get_client_left(global::System.IntPtr self);

        // DEBUG: WEBKIT_API glongwebkit_dom_element_get_client_top(WebKitDOMElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_element_get_client_top")]
        internal static extern int webkit_dom_element_get_client_top(global::System.IntPtr self);

        // DEBUG: WEBKIT_API glongwebkit_dom_element_get_client_width(WebKitDOMElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_element_get_client_width")]
        internal static extern int webkit_dom_element_get_client_width(global::System.IntPtr self);

        // DEBUG: WEBKIT_API glongwebkit_dom_element_get_client_height(WebKitDOMElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_element_get_client_height")]
        internal static extern int webkit_dom_element_get_client_height(global::System.IntPtr self);

        // DEBUG: WEBKIT_API glongwebkit_dom_element_get_scroll_left(WebKitDOMElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_element_get_scroll_left")]
        internal static extern int webkit_dom_element_get_scroll_left(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_element_set_scroll_left(WebKitDOMElement* self, glong value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_element_set_scroll_left")]
        internal static extern void webkit_dom_element_set_scroll_left(global::System.IntPtr self, int value);

        // DEBUG: WEBKIT_API glongwebkit_dom_element_get_scroll_top(WebKitDOMElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_element_get_scroll_top")]
        internal static extern int webkit_dom_element_get_scroll_top(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_element_set_scroll_top(WebKitDOMElement* self, glong value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_element_set_scroll_top")]
        internal static extern void webkit_dom_element_set_scroll_top(global::System.IntPtr self, int value);

        // DEBUG: WEBKIT_API glongwebkit_dom_element_get_scroll_width(WebKitDOMElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_element_get_scroll_width")]
        internal static extern int webkit_dom_element_get_scroll_width(global::System.IntPtr self);

        // DEBUG: WEBKIT_API glongwebkit_dom_element_get_scroll_height(WebKitDOMElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_element_get_scroll_height")]
        internal static extern int webkit_dom_element_get_scroll_height(global::System.IntPtr self);

        // DEBUG: WEBKIT_API WebKitDOMElement*webkit_dom_element_get_first_element_child(WebKitDOMElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_element_get_first_element_child")]
        internal static extern global::System.IntPtr webkit_dom_element_get_first_element_child(global::System.IntPtr self);

        // DEBUG: WEBKIT_API WebKitDOMElement*webkit_dom_element_get_last_element_child(WebKitDOMElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_element_get_last_element_child")]
        internal static extern global::System.IntPtr webkit_dom_element_get_last_element_child(global::System.IntPtr self);

        // DEBUG: WEBKIT_API WebKitDOMElement*webkit_dom_element_get_previous_element_sibling(WebKitDOMElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_element_get_previous_element_sibling")]
        internal static extern global::System.IntPtr webkit_dom_element_get_previous_element_sibling(global::System.IntPtr self);

        // DEBUG: WEBKIT_API WebKitDOMElement*webkit_dom_element_get_next_element_sibling(WebKitDOMElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_element_get_next_element_sibling")]
        internal static extern global::System.IntPtr webkit_dom_element_get_next_element_sibling(global::System.IntPtr self);

        // DEBUG: WEBKIT_API gulongwebkit_dom_element_get_child_element_count(WebKitDOMElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_element_get_child_element_count")]
        internal static extern uint webkit_dom_element_get_child_element_count(global::System.IntPtr self);

        // DEBUG: WEBKIT_API gchar*webkit_dom_element_get_webkit_region_overflow(WebKitDOMElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_element_get_webkit_region_overflow")]
        internal static extern sbyte* webkit_dom_element_get_webkit_region_overflow(global::System.IntPtr self);
    }
}
