//----------------------------------------------------------------------------
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
//----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace Webbed.Scripting.Interop
{
    // DEBUG: struct _WebKitDOMFile { WebKitDOMBlob parent_instance;}
    [StructLayout(LayoutKind.Explicit, Size = 16)]
    public unsafe struct _WebKitDOMFile
    {
        // DEBUG: WebKitDOMBlob parent_instance
        [FieldOffset(0)]
        public _WebKitDOMBlob parent_instance;
    }

    // DEBUG: struct _WebKitDOMFileClass { WebKitDOMBlobClass parent_class;}
    [StructLayout(LayoutKind.Explicit, Size = 68)]
    public unsafe struct _WebKitDOMFileClass
    {
        // DEBUG: WebKitDOMBlobClass parent_class
        [FieldOffset(0)]
        public _WebKitDOMBlobClass parent_class;
    }

    public unsafe partial class WebKitDOMFile: GLib.Object
    {
        public WebKitDOMFile(IntPtr handle) : base(handle) { }
        // DEBUG: WEBKIT_API GTypewebkit_dom_file_get_type (void)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_file_get_type")]
        internal static extern uint webkit_dom_file_get_type();

        public GLib.GType Type
        {
            get
            {
                return new GLib.GType((IntPtr)webkit_dom_file_get_type());
            }
        }

        // DEBUG: WEBKIT_API gchar*webkit_dom_file_get_name(WebKitDOMFile* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_file_get_name")]
        internal static extern sbyte* webkit_dom_file_get_name(global::System.IntPtr self);

        // DEBUG: WEBKIT_API gchar*webkit_dom_file_get_file_name(WebKitDOMFile* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_file_get_file_name")]
        internal static extern sbyte* webkit_dom_file_get_file_name(global::System.IntPtr self);

        // DEBUG: WEBKIT_API guint64webkit_dom_file_get_file_size(WebKitDOMFile* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_file_get_file_size")]
        internal static extern ulong webkit_dom_file_get_file_size(global::System.IntPtr self);
    }
}
