//----------------------------------------------------------------------------
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
//----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace Webbed.Scripting.Interop
{
    // DEBUG: struct _WebKitDOMDOMSelection { WebKitDOMObject parent_instance;}
    [StructLayout(LayoutKind.Explicit, Size = 16)]
    public unsafe struct _WebKitDOMDOMSelection
    {
        // DEBUG: WebKitDOMObject parent_instance
        [FieldOffset(0)]
        public _WebKitDOMObject parent_instance;
    }

    // DEBUG: struct _WebKitDOMDOMSelectionClass { WebKitDOMObjectClass parent_class;}
    [StructLayout(LayoutKind.Explicit, Size = 68)]
    public unsafe struct _WebKitDOMDOMSelectionClass
    {
        // DEBUG: WebKitDOMObjectClass parent_class
        [FieldOffset(0)]
        public _WebKitDOMObjectClass parent_class;
    }

    public unsafe partial class WebKitDOMDOMSelection: GLib.Object
    {
        public WebKitDOMDOMSelection(IntPtr handle) : base(handle) { }
        // DEBUG: WEBKIT_API GTypewebkit_dom_dom_selection_get_type (void)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_dom_selection_get_type")]
        internal static extern uint webkit_dom_dom_selection_get_type();

        public GLib.GType Type
        {
            get
            {
                return new GLib.GType((IntPtr)webkit_dom_dom_selection_get_type());
            }
        }

        // DEBUG: WEBKIT_API voidwebkit_dom_dom_selection_collapse(WebKitDOMDOMSelection* self, WebKitDOMNode* node, glong index, GError **error)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_dom_selection_collapse")]
        internal static extern void webkit_dom_dom_selection_collapse(global::System.IntPtr self, global::System.IntPtr node, int index, global::System.IntPtr error);

        // DEBUG: WEBKIT_API voidwebkit_dom_dom_selection_collapse_to_end(WebKitDOMDOMSelection* self, GError **error)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_dom_selection_collapse_to_end")]
        internal static extern void webkit_dom_dom_selection_collapse_to_end(global::System.IntPtr self, global::System.IntPtr error);

        // DEBUG: WEBKIT_API voidwebkit_dom_dom_selection_collapse_to_start(WebKitDOMDOMSelection* self, GError **error)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_dom_selection_collapse_to_start")]
        internal static extern void webkit_dom_dom_selection_collapse_to_start(global::System.IntPtr self, global::System.IntPtr error);

        // DEBUG: WEBKIT_API voidwebkit_dom_dom_selection_delete_from_document(WebKitDOMDOMSelection* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_dom_selection_delete_from_document")]
        internal static extern void webkit_dom_dom_selection_delete_from_document(global::System.IntPtr self);

        // DEBUG: WEBKIT_API gbooleanwebkit_dom_dom_selection_contains_node(WebKitDOMDOMSelection* self, WebKitDOMNode* node, gboolean allow_partial)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_dom_selection_contains_node")]
        internal static extern int webkit_dom_dom_selection_contains_node(global::System.IntPtr self, global::System.IntPtr node, int allow_partial);

        // DEBUG: WEBKIT_API voidwebkit_dom_dom_selection_select_all_children(WebKitDOMDOMSelection* self, WebKitDOMNode* node, GError **error)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_dom_selection_select_all_children")]
        internal static extern void webkit_dom_dom_selection_select_all_children(global::System.IntPtr self, global::System.IntPtr node, global::System.IntPtr error);

        // DEBUG: WEBKIT_API voidwebkit_dom_dom_selection_extend(WebKitDOMDOMSelection* self, WebKitDOMNode* node, glong offset, GError **error)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_dom_selection_extend")]
        internal static extern void webkit_dom_dom_selection_extend(global::System.IntPtr self, global::System.IntPtr node, int offset, global::System.IntPtr error);

        // DEBUG: WEBKIT_API WebKitDOMRange*webkit_dom_dom_selection_get_range_at(WebKitDOMDOMSelection* self, glong index, GError **error)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_dom_selection_get_range_at")]
        internal static extern global::System.IntPtr webkit_dom_dom_selection_get_range_at(global::System.IntPtr self, int index, global::System.IntPtr error);

        // DEBUG: WEBKIT_API voidwebkit_dom_dom_selection_remove_all_ranges(WebKitDOMDOMSelection* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_dom_selection_remove_all_ranges")]
        internal static extern void webkit_dom_dom_selection_remove_all_ranges(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_dom_selection_add_range(WebKitDOMDOMSelection* self, WebKitDOMRange* range)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_dom_selection_add_range")]
        internal static extern void webkit_dom_dom_selection_add_range(global::System.IntPtr self, global::System.IntPtr range);

        // DEBUG: WEBKIT_API voidwebkit_dom_dom_selection_modify(WebKitDOMDOMSelection* self, const gchar* alter, const gchar* direction, const gchar* granularity)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_dom_selection_modify")]
        internal static extern void webkit_dom_dom_selection_modify(global::System.IntPtr self, global::System.IntPtr alter, global::System.IntPtr direction, global::System.IntPtr granularity);

        // DEBUG: WEBKIT_API voidwebkit_dom_dom_selection_set_base_and_extent(WebKitDOMDOMSelection* self, WebKitDOMNode* base_node, glong base_offset, WebKitDOMNode* extent_node, glong extent_offset, GError **error)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_dom_selection_set_base_and_extent")]
        internal static extern void webkit_dom_dom_selection_set_base_and_extent(global::System.IntPtr self, global::System.IntPtr base_node, int base_offset, global::System.IntPtr extent_node, int extent_offset, global::System.IntPtr error);

        // DEBUG: WEBKIT_API voidwebkit_dom_dom_selection_set_position(WebKitDOMDOMSelection* self, WebKitDOMNode* node, glong offset, GError **error)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_dom_selection_set_position")]
        internal static extern void webkit_dom_dom_selection_set_position(global::System.IntPtr self, global::System.IntPtr node, int offset, global::System.IntPtr error);

        // DEBUG: WEBKIT_API voidwebkit_dom_dom_selection_empty(WebKitDOMDOMSelection* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_dom_selection_empty")]
        internal static extern void webkit_dom_dom_selection_empty(global::System.IntPtr self);

        // DEBUG: WEBKIT_API WebKitDOMNode*webkit_dom_dom_selection_get_anchor_node(WebKitDOMDOMSelection* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_dom_selection_get_anchor_node")]
        internal static extern global::System.IntPtr webkit_dom_dom_selection_get_anchor_node(global::System.IntPtr self);

        // DEBUG: WEBKIT_API glongwebkit_dom_dom_selection_get_anchor_offset(WebKitDOMDOMSelection* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_dom_selection_get_anchor_offset")]
        internal static extern int webkit_dom_dom_selection_get_anchor_offset(global::System.IntPtr self);

        // DEBUG: WEBKIT_API WebKitDOMNode*webkit_dom_dom_selection_get_focus_node(WebKitDOMDOMSelection* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_dom_selection_get_focus_node")]
        internal static extern global::System.IntPtr webkit_dom_dom_selection_get_focus_node(global::System.IntPtr self);

        // DEBUG: WEBKIT_API glongwebkit_dom_dom_selection_get_focus_offset(WebKitDOMDOMSelection* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_dom_selection_get_focus_offset")]
        internal static extern int webkit_dom_dom_selection_get_focus_offset(global::System.IntPtr self);

        // DEBUG: WEBKIT_API gbooleanwebkit_dom_dom_selection_get_is_collapsed(WebKitDOMDOMSelection* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_dom_selection_get_is_collapsed")]
        internal static extern int webkit_dom_dom_selection_get_is_collapsed(global::System.IntPtr self);

        // DEBUG: WEBKIT_API glongwebkit_dom_dom_selection_get_range_count(WebKitDOMDOMSelection* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_dom_selection_get_range_count")]
        internal static extern int webkit_dom_dom_selection_get_range_count(global::System.IntPtr self);

        // DEBUG: WEBKIT_API WebKitDOMNode*webkit_dom_dom_selection_get_base_node(WebKitDOMDOMSelection* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_dom_selection_get_base_node")]
        internal static extern global::System.IntPtr webkit_dom_dom_selection_get_base_node(global::System.IntPtr self);

        // DEBUG: WEBKIT_API glongwebkit_dom_dom_selection_get_base_offset(WebKitDOMDOMSelection* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_dom_selection_get_base_offset")]
        internal static extern int webkit_dom_dom_selection_get_base_offset(global::System.IntPtr self);

        // DEBUG: WEBKIT_API WebKitDOMNode*webkit_dom_dom_selection_get_extent_node(WebKitDOMDOMSelection* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_dom_selection_get_extent_node")]
        internal static extern global::System.IntPtr webkit_dom_dom_selection_get_extent_node(global::System.IntPtr self);

        // DEBUG: WEBKIT_API glongwebkit_dom_dom_selection_get_extent_offset(WebKitDOMDOMSelection* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_dom_selection_get_extent_offset")]
        internal static extern int webkit_dom_dom_selection_get_extent_offset(global::System.IntPtr self);
    }
}
