//----------------------------------------------------------------------------
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
//----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace Webbed.Scripting.Interop
{
    // DEBUG: typedef struct _WebKitDOMAttr WebKitDOMAttr
    // DEBUG: typedef struct _WebKitDOMNode WebKitDOMNode
    // DEBUG: typedef struct _WebKitDOMObject WebKitDOMObject
    // DEBUG: typedef struct _WebKitDOMAttrClass WebKitDOMAttrClass
    // DEBUG: typedef struct _WebKitDOMNodeClass WebKitDOMNodeClass
    // DEBUG: typedef struct _WebKitDOMObjectClass WebKitDOMObjectClass
    // DEBUG: typedef struct _WebKitDOMBarInfo WebKitDOMBarInfo
    // DEBUG: typedef struct _WebKitDOMBarInfoClass WebKitDOMBarInfoClass
    // DEBUG: typedef struct _WebKitDOMBlob WebKitDOMBlob
    // DEBUG: typedef struct _WebKitDOMBlobClass WebKitDOMBlobClass
    // DEBUG: typedef struct _WebKitDOMCDATASection WebKitDOMCDATASection
    // DEBUG: typedef struct _WebKitDOMText WebKitDOMText
    // DEBUG: typedef struct _WebKitDOMCharacterData WebKitDOMCharacterData
    // DEBUG: typedef struct _WebKitDOMCDATASectionClass WebKitDOMCDATASectionClass
    // DEBUG: typedef struct _WebKitDOMTextClass WebKitDOMTextClass
    // DEBUG: typedef struct _WebKitDOMCharacterDataClass WebKitDOMCharacterDataClass
    // DEBUG: typedef struct _WebKitDOMCSSRule WebKitDOMCSSRule
    // DEBUG: typedef struct _WebKitDOMCSSRuleClass WebKitDOMCSSRuleClass
    // DEBUG: typedef struct _WebKitDOMCSSRuleList WebKitDOMCSSRuleList
    // DEBUG: typedef struct _WebKitDOMCSSRuleListClass WebKitDOMCSSRuleListClass
    // DEBUG: typedef struct _WebKitDOMCSSStyleDeclaration WebKitDOMCSSStyleDeclaration
    // DEBUG: typedef struct _WebKitDOMCSSStyleDeclarationClass WebKitDOMCSSStyleDeclarationClass
    // DEBUG: typedef struct _WebKitDOMCSSStyleSheet WebKitDOMCSSStyleSheet
    // DEBUG: typedef struct _WebKitDOMStyleSheet WebKitDOMStyleSheet
    // DEBUG: typedef struct _WebKitDOMCSSStyleSheetClass WebKitDOMCSSStyleSheetClass
    // DEBUG: typedef struct _WebKitDOMStyleSheetClass WebKitDOMStyleSheetClass
    // DEBUG: typedef struct _WebKitDOMCSSValue WebKitDOMCSSValue
    // DEBUG: typedef struct _WebKitDOMCSSValueClass WebKitDOMCSSValueClass
    // DEBUG: typedef struct _WebKitDOMComment WebKitDOMComment
    // DEBUG: typedef struct _WebKitDOMCommentClass WebKitDOMCommentClass
    // DEBUG: typedef struct _WebKitDOMConsole WebKitDOMConsole
    // DEBUG: typedef struct _WebKitDOMConsoleClass WebKitDOMConsoleClass
    // DEBUG: typedef struct _WebKitDOMCustom WebKitDOMCustom
    // DEBUG: typedef struct _WebKitDOMCustomClass WebKitDOMCustomClass
    // DEBUG: typedef struct _WebKitDOMDOMApplicationCache WebKitDOMDOMApplicationCache
    // DEBUG: typedef struct _WebKitDOMDOMApplicationCacheClass WebKitDOMDOMApplicationCacheClass
    // DEBUG: typedef struct _WebKitDOMDOMImplementation WebKitDOMDOMImplementation
    // DEBUG: typedef struct _WebKitDOMDOMImplementationClass WebKitDOMDOMImplementationClass
    // DEBUG: typedef struct _WebKitDOMDOMMimeType WebKitDOMDOMMimeType
    // DEBUG: typedef struct _WebKitDOMDOMMimeTypeClass WebKitDOMDOMMimeTypeClass
    // DEBUG: typedef struct _WebKitDOMDOMMimeTypeArray WebKitDOMDOMMimeTypeArray
    // DEBUG: typedef struct _WebKitDOMDOMMimeTypeArrayClass WebKitDOMDOMMimeTypeArrayClass
    // DEBUG: typedef struct _WebKitDOMDOMPlugin WebKitDOMDOMPlugin
    // DEBUG: typedef struct _WebKitDOMDOMPluginClass WebKitDOMDOMPluginClass
    // DEBUG: typedef struct _WebKitDOMDOMPluginArray WebKitDOMDOMPluginArray
    // DEBUG: typedef struct _WebKitDOMDOMPluginArrayClass WebKitDOMDOMPluginArrayClass
    // DEBUG: typedef struct _WebKitDOMDOMSelection WebKitDOMDOMSelection
    // DEBUG: typedef struct _WebKitDOMDOMSelectionClass WebKitDOMDOMSelectionClass
    // DEBUG: typedef struct _WebKitDOMDOMSettableTokenList WebKitDOMDOMSettableTokenList
    // DEBUG: typedef struct _WebKitDOMDOMTokenList WebKitDOMDOMTokenList
    // DEBUG: typedef struct _WebKitDOMDOMSettableTokenListClass WebKitDOMDOMSettableTokenListClass
    // DEBUG: typedef struct _WebKitDOMDOMTokenListClass WebKitDOMDOMTokenListClass
    // DEBUG: typedef struct _WebKitDOMDOMStringList WebKitDOMDOMStringList
    // DEBUG: typedef struct _WebKitDOMDOMStringListClass WebKitDOMDOMStringListClass
    // DEBUG: typedef struct _WebKitDOMDOMStringMap WebKitDOMDOMStringMap
    // DEBUG: typedef struct _WebKitDOMDOMStringMapClass WebKitDOMDOMStringMapClass
    // DEBUG: typedef struct _WebKitDOMDOMWindow WebKitDOMDOMWindow
    // DEBUG: typedef struct _WebKitDOMDOMWindowClass WebKitDOMDOMWindowClass
    // DEBUG: typedef struct _WebKitDOMDatabase WebKitDOMDatabase
    // DEBUG: typedef struct _WebKitDOMDatabaseClass WebKitDOMDatabaseClass
    // DEBUG: typedef struct _WebKitDOMDocument WebKitDOMDocument
    // DEBUG: typedef struct _WebKitDOMDocumentClass WebKitDOMDocumentClass
    // DEBUG: typedef struct _WebKitDOMDocumentFragment WebKitDOMDocumentFragment
    // DEBUG: typedef struct _WebKitDOMDocumentFragmentClass WebKitDOMDocumentFragmentClass
    // DEBUG: typedef struct _WebKitDOMDocumentType WebKitDOMDocumentType
    // DEBUG: typedef struct _WebKitDOMDocumentTypeClass WebKitDOMDocumentTypeClass
    // DEBUG: typedef struct _WebKitDOMElement WebKitDOMElement
    // DEBUG: typedef struct _WebKitDOMElementClass WebKitDOMElementClass
    // DEBUG: typedef struct _WebKitDOMEntityReference WebKitDOMEntityReference
    // DEBUG: typedef struct _WebKitDOMEntityReferenceClass WebKitDOMEntityReferenceClass
    // DEBUG: typedef struct _WebKitDOMEvent WebKitDOMEvent
    // DEBUG: typedef struct _WebKitDOMEventClass WebKitDOMEventClass
    // DEBUG: typedef struct _WebKitDOMEventTarget WebKitDOMEventTarget
    // DEBUG: typedef struct _WebKitDOMEventTargetClass WebKitDOMEventTargetClass
    // DEBUG: typedef struct _WebKitDOMFile WebKitDOMFile
    // DEBUG: typedef struct _WebKitDOMFileClass WebKitDOMFileClass
    // DEBUG: typedef struct _WebKitDOMFileList WebKitDOMFileList
    // DEBUG: typedef struct _WebKitDOMFileListClass WebKitDOMFileListClass
    // DEBUG: typedef struct _WebKitDOMGeolocation WebKitDOMGeolocation
    // DEBUG: typedef struct _WebKitDOMGeolocationClass WebKitDOMGeolocationClass
    // DEBUG: typedef struct _WebKitDOMHTMLAnchorElement WebKitDOMHTMLAnchorElement
    // DEBUG: typedef struct _WebKitDOMHTMLElement WebKitDOMHTMLElement
    // DEBUG: typedef struct _WebKitDOMHTMLAnchorElementClass WebKitDOMHTMLAnchorElementClass
    // DEBUG: typedef struct _WebKitDOMHTMLElementClass WebKitDOMHTMLElementClass
    // DEBUG: typedef struct _WebKitDOMHTMLAppletElement WebKitDOMHTMLAppletElement
    // DEBUG: typedef struct _WebKitDOMHTMLAppletElementClass WebKitDOMHTMLAppletElementClass
    // DEBUG: typedef struct _WebKitDOMHTMLAreaElement WebKitDOMHTMLAreaElement
    // DEBUG: typedef struct _WebKitDOMHTMLAreaElementClass WebKitDOMHTMLAreaElementClass
    // DEBUG: typedef struct _WebKitDOMHTMLAudioElement WebKitDOMHTMLAudioElement
    // DEBUG: typedef struct _WebKitDOMHTMLMediaElement WebKitDOMHTMLMediaElement
    // DEBUG: typedef struct _WebKitDOMHTMLAudioElementClass WebKitDOMHTMLAudioElementClass
    // DEBUG: typedef struct _WebKitDOMHTMLMediaElementClass WebKitDOMHTMLMediaElementClass
    // DEBUG: typedef struct _WebKitDOMHTMLBRElement WebKitDOMHTMLBRElement
    // DEBUG: typedef struct _WebKitDOMHTMLBRElementClass WebKitDOMHTMLBRElementClass
    // DEBUG: typedef struct _WebKitDOMHTMLBaseElement WebKitDOMHTMLBaseElement
    // DEBUG: typedef struct _WebKitDOMHTMLBaseElementClass WebKitDOMHTMLBaseElementClass
    // DEBUG: typedef struct _WebKitDOMHTMLBaseFontElement WebKitDOMHTMLBaseFontElement
    // DEBUG: typedef struct _WebKitDOMHTMLBaseFontElementClass WebKitDOMHTMLBaseFontElementClass
    // DEBUG: typedef struct _WebKitDOMHTMLBodyElement WebKitDOMHTMLBodyElement
    // DEBUG: typedef struct _WebKitDOMHTMLBodyElementClass WebKitDOMHTMLBodyElementClass
    // DEBUG: typedef struct _WebKitDOMHTMLButtonElement WebKitDOMHTMLButtonElement
    // DEBUG: typedef struct _WebKitDOMHTMLButtonElementClass WebKitDOMHTMLButtonElementClass
    // DEBUG: typedef struct _WebKitDOMHTMLCanvasElement WebKitDOMHTMLCanvasElement
    // DEBUG: typedef struct _WebKitDOMHTMLCanvasElementClass WebKitDOMHTMLCanvasElementClass
    // DEBUG: typedef struct _WebKitDOMHTMLCollection WebKitDOMHTMLCollection
    // DEBUG: typedef struct _WebKitDOMHTMLCollectionClass WebKitDOMHTMLCollectionClass
    // DEBUG: typedef struct _WebKitDOMHTMLDListElement WebKitDOMHTMLDListElement
    // DEBUG: typedef struct _WebKitDOMHTMLDListElementClass WebKitDOMHTMLDListElementClass
    // DEBUG: typedef struct _WebKitDOMHTMLDetailsElement WebKitDOMHTMLDetailsElement
    // DEBUG: typedef struct _WebKitDOMHTMLDetailsElementClass WebKitDOMHTMLDetailsElementClass
    // DEBUG: typedef struct _WebKitDOMHTMLDirectoryElement WebKitDOMHTMLDirectoryElement
    // DEBUG: typedef struct _WebKitDOMHTMLDirectoryElementClass WebKitDOMHTMLDirectoryElementClass
    // DEBUG: typedef struct _WebKitDOMHTMLDivElement WebKitDOMHTMLDivElement
    // DEBUG: typedef struct _WebKitDOMHTMLDivElementClass WebKitDOMHTMLDivElementClass
    // DEBUG: typedef struct _WebKitDOMHTMLDocument WebKitDOMHTMLDocument
    // DEBUG: typedef struct _WebKitDOMHTMLDocumentClass WebKitDOMHTMLDocumentClass
    // DEBUG: typedef struct _WebKitDOMHTMLEmbedElement WebKitDOMHTMLEmbedElement
    // DEBUG: typedef struct _WebKitDOMHTMLEmbedElementClass WebKitDOMHTMLEmbedElementClass
    // DEBUG: typedef struct _WebKitDOMHTMLFieldSetElement WebKitDOMHTMLFieldSetElement
    // DEBUG: typedef struct _WebKitDOMHTMLFieldSetElementClass WebKitDOMHTMLFieldSetElementClass
    // DEBUG: typedef struct _WebKitDOMHTMLFontElement WebKitDOMHTMLFontElement
    // DEBUG: typedef struct _WebKitDOMHTMLFontElementClass WebKitDOMHTMLFontElementClass
    // DEBUG: typedef struct _WebKitDOMHTMLFormElement WebKitDOMHTMLFormElement
    // DEBUG: typedef struct _WebKitDOMHTMLFormElementClass WebKitDOMHTMLFormElementClass
    // DEBUG: typedef struct _WebKitDOMHTMLFrameElement WebKitDOMHTMLFrameElement
    // DEBUG: typedef struct _WebKitDOMHTMLFrameElementClass WebKitDOMHTMLFrameElementClass
    // DEBUG: typedef struct _WebKitDOMHTMLFrameSetElement WebKitDOMHTMLFrameSetElement
    // DEBUG: typedef struct _WebKitDOMHTMLFrameSetElementClass WebKitDOMHTMLFrameSetElementClass
    // DEBUG: typedef struct _WebKitDOMHTMLHRElement WebKitDOMHTMLHRElement
    // DEBUG: typedef struct _WebKitDOMHTMLHRElementClass WebKitDOMHTMLHRElementClass
    // DEBUG: typedef struct _WebKitDOMHTMLHeadElement WebKitDOMHTMLHeadElement
    // DEBUG: typedef struct _WebKitDOMHTMLHeadElementClass WebKitDOMHTMLHeadElementClass
    // DEBUG: typedef struct _WebKitDOMHTMLHeadingElement WebKitDOMHTMLHeadingElement
    // DEBUG: typedef struct _WebKitDOMHTMLHeadingElementClass WebKitDOMHTMLHeadingElementClass
    // DEBUG: typedef struct _WebKitDOMHTMLHtmlElement WebKitDOMHTMLHtmlElement
    // DEBUG: typedef struct _WebKitDOMHTMLHtmlElementClass WebKitDOMHTMLHtmlElementClass
    // DEBUG: typedef struct _WebKitDOMHTMLIFrameElement WebKitDOMHTMLIFrameElement
    // DEBUG: typedef struct _WebKitDOMHTMLIFrameElementClass WebKitDOMHTMLIFrameElementClass
    // DEBUG: typedef struct _WebKitDOMHTMLImageElement WebKitDOMHTMLImageElement
    // DEBUG: typedef struct _WebKitDOMHTMLImageElementClass WebKitDOMHTMLImageElementClass
    // DEBUG: typedef struct _WebKitDOMHTMLInputElement WebKitDOMHTMLInputElement
    // DEBUG: typedef struct _WebKitDOMHTMLInputElementClass WebKitDOMHTMLInputElementClass
    // DEBUG: typedef struct _WebKitDOMHTMLKeygenElement WebKitDOMHTMLKeygenElement
    // DEBUG: typedef struct _WebKitDOMHTMLKeygenElementClass WebKitDOMHTMLKeygenElementClass
    // DEBUG: typedef struct _WebKitDOMHTMLLIElement WebKitDOMHTMLLIElement
    // DEBUG: typedef struct _WebKitDOMHTMLLIElementClass WebKitDOMHTMLLIElementClass
    // DEBUG: typedef struct _WebKitDOMHTMLLabelElement WebKitDOMHTMLLabelElement
    // DEBUG: typedef struct _WebKitDOMHTMLLabelElementClass WebKitDOMHTMLLabelElementClass
    // DEBUG: typedef struct _WebKitDOMHTMLLegendElement WebKitDOMHTMLLegendElement
    // DEBUG: typedef struct _WebKitDOMHTMLLegendElementClass WebKitDOMHTMLLegendElementClass
    // DEBUG: typedef struct _WebKitDOMHTMLLinkElement WebKitDOMHTMLLinkElement
    // DEBUG: typedef struct _WebKitDOMHTMLLinkElementClass WebKitDOMHTMLLinkElementClass
    // DEBUG: typedef struct _WebKitDOMHTMLMapElement WebKitDOMHTMLMapElement
    // DEBUG: typedef struct _WebKitDOMHTMLMapElementClass WebKitDOMHTMLMapElementClass
    // DEBUG: typedef struct _WebKitDOMHTMLMarqueeElement WebKitDOMHTMLMarqueeElement
    // DEBUG: typedef struct _WebKitDOMHTMLMarqueeElementClass WebKitDOMHTMLMarqueeElementClass
    // DEBUG: typedef struct _WebKitDOMHTMLMenuElement WebKitDOMHTMLMenuElement
    // DEBUG: typedef struct _WebKitDOMHTMLMenuElementClass WebKitDOMHTMLMenuElementClass
    // DEBUG: typedef struct _WebKitDOMHTMLMetaElement WebKitDOMHTMLMetaElement
    // DEBUG: typedef struct _WebKitDOMHTMLMetaElementClass WebKitDOMHTMLMetaElementClass
    // DEBUG: typedef struct _WebKitDOMHTMLModElement WebKitDOMHTMLModElement
    // DEBUG: typedef struct _WebKitDOMHTMLModElementClass WebKitDOMHTMLModElementClass
    // DEBUG: typedef struct _WebKitDOMHTMLOListElement WebKitDOMHTMLOListElement
    // DEBUG: typedef struct _WebKitDOMHTMLOListElementClass WebKitDOMHTMLOListElementClass
    // DEBUG: typedef struct _WebKitDOMHTMLObjectElement WebKitDOMHTMLObjectElement
    // DEBUG: typedef struct _WebKitDOMHTMLObjectElementClass WebKitDOMHTMLObjectElementClass
    // DEBUG: typedef struct _WebKitDOMHTMLOptGroupElement WebKitDOMHTMLOptGroupElement
    // DEBUG: typedef struct _WebKitDOMHTMLOptGroupElementClass WebKitDOMHTMLOptGroupElementClass
    // DEBUG: typedef struct _WebKitDOMHTMLOptionElement WebKitDOMHTMLOptionElement
    // DEBUG: typedef struct _WebKitDOMHTMLOptionElementClass WebKitDOMHTMLOptionElementClass
    // DEBUG: typedef struct _WebKitDOMHTMLOptionsCollection WebKitDOMHTMLOptionsCollection
    // DEBUG: typedef struct _WebKitDOMHTMLOptionsCollectionClass WebKitDOMHTMLOptionsCollectionClass
    // DEBUG: typedef struct _WebKitDOMHTMLParagraphElement WebKitDOMHTMLParagraphElement
    // DEBUG: typedef struct _WebKitDOMHTMLParagraphElementClass WebKitDOMHTMLParagraphElementClass
    // DEBUG: typedef struct _WebKitDOMHTMLParamElement WebKitDOMHTMLParamElement
    // DEBUG: typedef struct _WebKitDOMHTMLParamElementClass WebKitDOMHTMLParamElementClass
    // DEBUG: typedef struct _WebKitDOMHTMLPreElement WebKitDOMHTMLPreElement
    // DEBUG: typedef struct _WebKitDOMHTMLPreElementClass WebKitDOMHTMLPreElementClass
    // DEBUG: typedef struct _WebKitDOMHTMLQuoteElement WebKitDOMHTMLQuoteElement
    // DEBUG: typedef struct _WebKitDOMHTMLQuoteElementClass WebKitDOMHTMLQuoteElementClass
    // DEBUG: typedef struct _WebKitDOMHTMLScriptElement WebKitDOMHTMLScriptElement
    // DEBUG: typedef struct _WebKitDOMHTMLScriptElementClass WebKitDOMHTMLScriptElementClass
    // DEBUG: typedef struct _WebKitDOMHTMLSelectElement WebKitDOMHTMLSelectElement
    // DEBUG: typedef struct _WebKitDOMHTMLSelectElementClass WebKitDOMHTMLSelectElementClass
    // DEBUG: typedef struct _WebKitDOMHTMLStyleElement WebKitDOMHTMLStyleElement
    // DEBUG: typedef struct _WebKitDOMHTMLStyleElementClass WebKitDOMHTMLStyleElementClass
    // DEBUG: typedef struct _WebKitDOMHTMLTableCaptionElement WebKitDOMHTMLTableCaptionElement
    // DEBUG: typedef struct _WebKitDOMHTMLTableCaptionElementClass WebKitDOMHTMLTableCaptionElementClass
    // DEBUG: typedef struct _WebKitDOMHTMLTableCellElement WebKitDOMHTMLTableCellElement
    // DEBUG: typedef struct _WebKitDOMHTMLTableCellElementClass WebKitDOMHTMLTableCellElementClass
    // DEBUG: typedef struct _WebKitDOMHTMLTableColElement WebKitDOMHTMLTableColElement
    // DEBUG: typedef struct _WebKitDOMHTMLTableColElementClass WebKitDOMHTMLTableColElementClass
    // DEBUG: typedef struct _WebKitDOMHTMLTableElement WebKitDOMHTMLTableElement
    // DEBUG: typedef struct _WebKitDOMHTMLTableElementClass WebKitDOMHTMLTableElementClass
    // DEBUG: typedef struct _WebKitDOMHTMLTableRowElement WebKitDOMHTMLTableRowElement
    // DEBUG: typedef struct _WebKitDOMHTMLTableRowElementClass WebKitDOMHTMLTableRowElementClass
    // DEBUG: typedef struct _WebKitDOMHTMLTableSectionElement WebKitDOMHTMLTableSectionElement
    // DEBUG: typedef struct _WebKitDOMHTMLTableSectionElementClass WebKitDOMHTMLTableSectionElementClass
    // DEBUG: typedef struct _WebKitDOMHTMLTextAreaElement WebKitDOMHTMLTextAreaElement
    // DEBUG: typedef struct _WebKitDOMHTMLTextAreaElementClass WebKitDOMHTMLTextAreaElementClass
    // DEBUG: typedef struct _WebKitDOMHTMLTitleElement WebKitDOMHTMLTitleElement
    // DEBUG: typedef struct _WebKitDOMHTMLTitleElementClass WebKitDOMHTMLTitleElementClass
    // DEBUG: typedef struct _WebKitDOMHTMLUListElement WebKitDOMHTMLUListElement
    // DEBUG: typedef struct _WebKitDOMHTMLUListElementClass WebKitDOMHTMLUListElementClass
    // DEBUG: typedef struct _WebKitDOMHTMLVideoElement WebKitDOMHTMLVideoElement
    // DEBUG: typedef struct _WebKitDOMHTMLVideoElementClass WebKitDOMHTMLVideoElementClass
    // DEBUG: typedef struct _WebKitDOMHistory WebKitDOMHistory
    // DEBUG: typedef struct _WebKitDOMHistoryClass WebKitDOMHistoryClass
    // DEBUG: typedef struct _WebKitDOMLocation WebKitDOMLocation
    // DEBUG: typedef struct _WebKitDOMLocationClass WebKitDOMLocationClass
    // DEBUG: typedef struct _WebKitDOMMediaError WebKitDOMMediaError
    // DEBUG: typedef struct _WebKitDOMMediaErrorClass WebKitDOMMediaErrorClass
    // DEBUG: typedef struct _WebKitDOMMediaList WebKitDOMMediaList
    // DEBUG: typedef struct _WebKitDOMMediaListClass WebKitDOMMediaListClass
    // DEBUG: typedef struct _WebKitDOMMediaQueryList WebKitDOMMediaQueryList
    // DEBUG: typedef struct _WebKitDOMMediaQueryListClass WebKitDOMMediaQueryListClass
    // DEBUG: typedef struct _WebKitDOMMemoryInfo WebKitDOMMemoryInfo
    // DEBUG: typedef struct _WebKitDOMMemoryInfoClass WebKitDOMMemoryInfoClass
    // DEBUG: typedef struct _WebKitDOMMessagePort WebKitDOMMessagePort
    // DEBUG: typedef struct _WebKitDOMMessagePortClass WebKitDOMMessagePortClass
    // DEBUG: typedef struct _WebKitDOMMouseEvent WebKitDOMMouseEvent
    // DEBUG: typedef struct _WebKitDOMUIEvent WebKitDOMUIEvent
    // DEBUG: typedef struct _WebKitDOMMouseEventClass WebKitDOMMouseEventClass
    // DEBUG: typedef struct _WebKitDOMUIEventClass WebKitDOMUIEventClass
    // DEBUG: typedef struct _WebKitDOMNamedNodeMap WebKitDOMNamedNodeMap
    // DEBUG: typedef struct _WebKitDOMNamedNodeMapClass WebKitDOMNamedNodeMapClass
    // DEBUG: typedef struct _WebKitDOMNavigator WebKitDOMNavigator
    // DEBUG: typedef struct _WebKitDOMNavigatorClass WebKitDOMNavigatorClass
    // DEBUG: typedef struct _WebKitDOMNodeFilter WebKitDOMNodeFilter
    // DEBUG: typedef struct _WebKitDOMNodeFilterClass WebKitDOMNodeFilterClass
    // DEBUG: typedef struct _WebKitDOMNodeIterator WebKitDOMNodeIterator
    // DEBUG: typedef struct _WebKitDOMNodeIteratorClass WebKitDOMNodeIteratorClass
    // DEBUG: typedef struct _WebKitDOMNodeList WebKitDOMNodeList
    // DEBUG: typedef struct _WebKitDOMNodeListClass WebKitDOMNodeListClass
    // DEBUG: typedef struct _WebKitDOMProcessingInstruction WebKitDOMProcessingInstruction
    // DEBUG: typedef struct _WebKitDOMProcessingInstructionClass WebKitDOMProcessingInstructionClass
    // DEBUG: typedef struct _WebKitDOMRange WebKitDOMRange
    // DEBUG: typedef struct _WebKitDOMRangeClass WebKitDOMRangeClass
    // DEBUG: typedef struct _WebKitDOMScreen WebKitDOMScreen
    // DEBUG: typedef struct _WebKitDOMScreenClass WebKitDOMScreenClass
    // DEBUG: typedef struct _WebKitDOMStorage WebKitDOMStorage
    // DEBUG: typedef struct _WebKitDOMStorageClass WebKitDOMStorageClass
    // DEBUG: typedef struct _WebKitDOMStyleMedia WebKitDOMStyleMedia
    // DEBUG: typedef struct _WebKitDOMStyleMediaClass WebKitDOMStyleMediaClass
    // DEBUG: typedef struct _WebKitDOMStyleSheetList WebKitDOMStyleSheetList
    // DEBUG: typedef struct _WebKitDOMStyleSheetListClass WebKitDOMStyleSheetListClass
    // DEBUG: typedef struct _WebKitDOMTimeRanges WebKitDOMTimeRanges
    // DEBUG: typedef struct _WebKitDOMTimeRangesClass WebKitDOMTimeRangesClass
    // DEBUG: typedef struct _WebKitDOMTreeWalker WebKitDOMTreeWalker
    // DEBUG: typedef struct _WebKitDOMTreeWalkerClass WebKitDOMTreeWalkerClass
    // DEBUG: typedef struct _WebKitDOMValidityState WebKitDOMValidityState
    // DEBUG: typedef struct _WebKitDOMValidityStateClass WebKitDOMValidityStateClass
    // DEBUG: typedef struct _WebKitDOMWebKitAnimation WebKitDOMWebKitAnimation
    // DEBUG: typedef struct _WebKitDOMWebKitAnimationClass WebKitDOMWebKitAnimationClass
    // DEBUG: typedef struct _WebKitDOMWebKitAnimationList WebKitDOMWebKitAnimationList
    // DEBUG: typedef struct _WebKitDOMWebKitAnimationListClass WebKitDOMWebKitAnimationListClass
    // DEBUG: typedef struct _WebKitDOMWebKitNamedFlow WebKitDOMWebKitNamedFlow
    // DEBUG: typedef struct _WebKitDOMWebKitNamedFlowClass WebKitDOMWebKitNamedFlowClass
    // DEBUG: typedef struct _WebKitDOMWebKitPoint WebKitDOMWebKitPoint
    // DEBUG: typedef struct _WebKitDOMWebKitPointClass WebKitDOMWebKitPointClass
    // DEBUG: typedef struct _WebKitDOMXPathExpression WebKitDOMXPathExpression
    // DEBUG: typedef struct _WebKitDOMXPathExpressionClass WebKitDOMXPathExpressionClass
    // DEBUG: typedef struct _WebKitDOMXPathNSResolver WebKitDOMXPathNSResolver
    // DEBUG: typedef struct _WebKitDOMXPathNSResolverClass WebKitDOMXPathNSResolverClass
    // DEBUG: typedef struct _WebKitDOMXPathResult WebKitDOMXPathResult
    // DEBUG: typedef struct _WebKitDOMXPathResultClass WebKitDOMXPathResultClass
    // DEBUG: struct _WebKitDOMCustom
    [StructLayout(LayoutKind.Explicit, Size = 0)]
    public unsafe struct _WebKitDOMCustom
    {
    }

    // DEBUG: struct _WebKitDOMCustomClass
    [StructLayout(LayoutKind.Explicit, Size = 0)]
    public unsafe struct _WebKitDOMCustomClass
    {
    }

    // DEBUG: struct _WebKitDOMEventTarget
    [StructLayout(LayoutKind.Explicit, Size = 0)]
    public unsafe struct _WebKitDOMEventTarget
    {
    }

    // DEBUG: struct _WebKitDOMEventTargetClass
    [StructLayout(LayoutKind.Explicit, Size = 0)]
    public unsafe struct _WebKitDOMEventTargetClass
    {
    }
}
