//----------------------------------------------------------------------------
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
//----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace Webbed.Scripting.Interop
{
    // DEBUG: struct _WebKitDOMNodeIterator { WebKitDOMObject parent_instance;}
    [StructLayout(LayoutKind.Explicit, Size = 16)]
    public unsafe struct _WebKitDOMNodeIterator
    {
        // DEBUG: WebKitDOMObject parent_instance
        [FieldOffset(0)]
        public _WebKitDOMObject parent_instance;
    }

    // DEBUG: struct _WebKitDOMNodeIteratorClass { WebKitDOMObjectClass parent_class;}
    [StructLayout(LayoutKind.Explicit, Size = 68)]
    public unsafe struct _WebKitDOMNodeIteratorClass
    {
        // DEBUG: WebKitDOMObjectClass parent_class
        [FieldOffset(0)]
        public _WebKitDOMObjectClass parent_class;
    }

    public unsafe partial class WebKitDOMNodeIterator: GLib.Object
    {
        public WebKitDOMNodeIterator(IntPtr handle) : base(handle) { }
        // DEBUG: WEBKIT_API GTypewebkit_dom_node_iterator_get_type (void)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_node_iterator_get_type")]
        internal static extern uint webkit_dom_node_iterator_get_type();
        public GLib.GType Type
        {
            get
            {
                return new GLib.GType((IntPtr)webkit_dom_node_iterator_get_type());
            }
        }

        // DEBUG: WEBKIT_API WebKitDOMNode*webkit_dom_node_iterator_next_node(WebKitDOMNodeIterator* self, GError **error)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_node_iterator_next_node")]
        internal static extern global::System.IntPtr webkit_dom_node_iterator_next_node(global::System.IntPtr self, global::System.IntPtr error);

        // DEBUG: WEBKIT_API WebKitDOMNode*webkit_dom_node_iterator_previous_node(WebKitDOMNodeIterator* self, GError **error)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_node_iterator_previous_node")]
        internal static extern global::System.IntPtr webkit_dom_node_iterator_previous_node(global::System.IntPtr self, global::System.IntPtr error);

        // DEBUG: WEBKIT_API voidwebkit_dom_node_iterator_detach(WebKitDOMNodeIterator* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_node_iterator_detach")]
        internal static extern void webkit_dom_node_iterator_detach(global::System.IntPtr self);

        // DEBUG: WEBKIT_API WebKitDOMNode*webkit_dom_node_iterator_get_root(WebKitDOMNodeIterator* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_node_iterator_get_root")]
        internal static extern global::System.IntPtr webkit_dom_node_iterator_get_root(global::System.IntPtr self);

        // DEBUG: WEBKIT_API gulongwebkit_dom_node_iterator_get_what_to_show(WebKitDOMNodeIterator* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_node_iterator_get_what_to_show")]
        internal static extern uint webkit_dom_node_iterator_get_what_to_show(global::System.IntPtr self);

        // DEBUG: WEBKIT_API WebKitDOMNodeFilter*webkit_dom_node_iterator_get_filter(WebKitDOMNodeIterator* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_node_iterator_get_filter")]
        internal static extern global::System.IntPtr webkit_dom_node_iterator_get_filter(global::System.IntPtr self);

        // DEBUG: WEBKIT_API gbooleanwebkit_dom_node_iterator_get_expand_entity_references(WebKitDOMNodeIterator* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_node_iterator_get_expand_entity_references")]
        internal static extern int webkit_dom_node_iterator_get_expand_entity_references(global::System.IntPtr self);

        // DEBUG: WEBKIT_API WebKitDOMNode*webkit_dom_node_iterator_get_reference_node(WebKitDOMNodeIterator* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_node_iterator_get_reference_node")]
        internal static extern global::System.IntPtr webkit_dom_node_iterator_get_reference_node(global::System.IntPtr self);

        // DEBUG: WEBKIT_API gbooleanwebkit_dom_node_iterator_get_pointer_before_reference_node(WebKitDOMNodeIterator* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_node_iterator_get_pointer_before_reference_node")]
        internal static extern int webkit_dom_node_iterator_get_pointer_before_reference_node(global::System.IntPtr self);
    }
}
