//----------------------------------------------------------------------------
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
//----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace Webbed.Scripting.Interop
{
    // DEBUG: struct _WebKitDOMDOMStringList { WebKitDOMObject parent_instance;}
    [StructLayout(LayoutKind.Explicit, Size = 16)]
    public unsafe struct _WebKitDOMDOMStringList
    {
        // DEBUG: WebKitDOMObject parent_instance
        [FieldOffset(0)]
        public _WebKitDOMObject parent_instance;
    }

    // DEBUG: struct _WebKitDOMDOMStringListClass { WebKitDOMObjectClass parent_class;}
    [StructLayout(LayoutKind.Explicit, Size = 68)]
    public unsafe struct _WebKitDOMDOMStringListClass
    {
        // DEBUG: WebKitDOMObjectClass parent_class
        [FieldOffset(0)]
        public _WebKitDOMObjectClass parent_class;
    }

    public unsafe partial class WebKitDOMDOMStringList: GLib.Object
    {
        public WebKitDOMDOMStringList(IntPtr handle) : base(handle) { }
        // DEBUG: WEBKIT_API GTypewebkit_dom_dom_string_list_get_type (void)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_dom_string_list_get_type")]
        internal static extern uint webkit_dom_dom_string_list_get_type();

        public GLib.GType Type
        {
            get
            {
                return new GLib.GType((IntPtr)webkit_dom_dom_string_list_get_type());
            }
        }

        // DEBUG: WEBKIT_API gchar*webkit_dom_dom_string_list_item(WebKitDOMDOMStringList* self, gulong index)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_dom_string_list_item")]
        internal static extern sbyte* webkit_dom_dom_string_list_item(global::System.IntPtr self, uint index);

        // DEBUG: WEBKIT_API gbooleanwebkit_dom_dom_string_list_contains(WebKitDOMDOMStringList* self, const gchar* string)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_dom_string_list_contains")]
        internal static extern int webkit_dom_dom_string_list_contains(global::System.IntPtr self, global::System.IntPtr @string);

        // DEBUG: WEBKIT_API gulongwebkit_dom_dom_string_list_get_length(WebKitDOMDOMStringList* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_dom_string_list_get_length")]
        internal static extern uint webkit_dom_dom_string_list_get_length(global::System.IntPtr self);
    }
}
