//----------------------------------------------------------------------------
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
//----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace Webbed.Scripting.Interop
{
    // DEBUG: struct _WebKitDOMHTMLOptionsCollection { WebKitDOMHTMLCollection parent_instance;}
    [StructLayout(LayoutKind.Explicit, Size = 16)]
    public unsafe struct _WebKitDOMHTMLOptionsCollection
    {
        // DEBUG: WebKitDOMHTMLCollection parent_instance
        [FieldOffset(0)]
        public _WebKitDOMHTMLCollection parent_instance;
    }

    // DEBUG: struct _WebKitDOMHTMLOptionsCollectionClass { WebKitDOMHTMLCollectionClass parent_class;}
    [StructLayout(LayoutKind.Explicit, Size = 68)]
    public unsafe struct _WebKitDOMHTMLOptionsCollectionClass
    {
        // DEBUG: WebKitDOMHTMLCollectionClass parent_class
        [FieldOffset(0)]
        public _WebKitDOMHTMLCollectionClass parent_class;
    }

    public unsafe partial class WebKitDOMHTMLOptionsCollection: GLib.Object
    {
        public WebKitDOMHTMLOptionsCollection(IntPtr handle) : base(handle) { }
        // DEBUG: WEBKIT_API GTypewebkit_dom_html_options_collection_get_type (void)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_options_collection_get_type")]
        internal static extern uint webkit_dom_html_options_collection_get_type();
        public GLib.GType Type
        {
            get
            {
                return new GLib.GType((IntPtr)webkit_dom_html_options_collection_get_type());
            }
        }

        // DEBUG: WEBKIT_API glongwebkit_dom_html_options_collection_get_selected_index(WebKitDOMHTMLOptionsCollection* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_options_collection_get_selected_index")]
        internal static extern int webkit_dom_html_options_collection_get_selected_index(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_options_collection_set_selected_index(WebKitDOMHTMLOptionsCollection* self, glong value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_options_collection_set_selected_index")]
        internal static extern void webkit_dom_html_options_collection_set_selected_index(global::System.IntPtr self, int value);
    }
}
