//----------------------------------------------------------------------------
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
//----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace Webbed.Scripting.Interop
{
    // DEBUG: struct _WebKitDOMDOMPlugin { WebKitDOMObject parent_instance;}
    [StructLayout(LayoutKind.Explicit, Size = 16)]
    public unsafe struct _WebKitDOMDOMPlugin
    {
        // DEBUG: WebKitDOMObject parent_instance
        [FieldOffset(0)]
        public _WebKitDOMObject parent_instance;
    }

    // DEBUG: struct _WebKitDOMDOMPluginClass { WebKitDOMObjectClass parent_class;}
    [StructLayout(LayoutKind.Explicit, Size = 68)]
    public unsafe struct _WebKitDOMDOMPluginClass
    {
        // DEBUG: WebKitDOMObjectClass parent_class
        [FieldOffset(0)]
        public _WebKitDOMObjectClass parent_class;
    }

    public unsafe partial class WebKitDOMDOMPlugin: GLib.Object
    {
        public WebKitDOMDOMPlugin(IntPtr handle) : base(handle) { }
        // DEBUG: WEBKIT_API GTypewebkit_dom_dom_plugin_get_type (void)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_dom_plugin_get_type")]
        internal static extern uint webkit_dom_dom_plugin_get_type();

        public GLib.GType Type
        {
            get
            {
                return new GLib.GType((IntPtr)webkit_dom_dom_plugin_get_type());
            }
        }

        // DEBUG: WEBKIT_API WebKitDOMDOMMimeType*webkit_dom_dom_plugin_item(WebKitDOMDOMPlugin* self, gulong index)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_dom_plugin_item")]
        internal static extern global::System.IntPtr webkit_dom_dom_plugin_item(global::System.IntPtr self, uint index);

        // DEBUG: WEBKIT_API WebKitDOMDOMMimeType*webkit_dom_dom_plugin_named_item(WebKitDOMDOMPlugin* self, const gchar* name)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_dom_plugin_named_item")]
        internal static extern global::System.IntPtr webkit_dom_dom_plugin_named_item(global::System.IntPtr self, global::System.IntPtr name);

        // DEBUG: WEBKIT_API gchar*webkit_dom_dom_plugin_get_name(WebKitDOMDOMPlugin* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_dom_plugin_get_name")]
        internal static extern sbyte* webkit_dom_dom_plugin_get_name(global::System.IntPtr self);

        // DEBUG: WEBKIT_API gchar*webkit_dom_dom_plugin_get_filename(WebKitDOMDOMPlugin* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_dom_plugin_get_filename")]
        internal static extern sbyte* webkit_dom_dom_plugin_get_filename(global::System.IntPtr self);

        // DEBUG: WEBKIT_API gchar*webkit_dom_dom_plugin_get_description(WebKitDOMDOMPlugin* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_dom_plugin_get_description")]
        internal static extern sbyte* webkit_dom_dom_plugin_get_description(global::System.IntPtr self);

        // DEBUG: WEBKIT_API gulongwebkit_dom_dom_plugin_get_length(WebKitDOMDOMPlugin* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_dom_plugin_get_length")]
        internal static extern uint webkit_dom_dom_plugin_get_length(global::System.IntPtr self);
    }
}
