//----------------------------------------------------------------------------
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
//----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace Webbed.Scripting.Interop
{
    // DEBUG: struct _WebKitDOMMemoryInfo { WebKitDOMObject parent_instance;}
    [StructLayout(LayoutKind.Explicit, Size = 16)]
    public unsafe struct _WebKitDOMMemoryInfo
    {
        // DEBUG: WebKitDOMObject parent_instance
        [FieldOffset(0)]
        public _WebKitDOMObject parent_instance;
    }

    // DEBUG: struct _WebKitDOMMemoryInfoClass { WebKitDOMObjectClass parent_class;}
    [StructLayout(LayoutKind.Explicit, Size = 68)]
    public unsafe struct _WebKitDOMMemoryInfoClass
    {
        // DEBUG: WebKitDOMObjectClass parent_class
        [FieldOffset(0)]
        public _WebKitDOMObjectClass parent_class;
    }

    public unsafe partial class WebKitDOMMemoryInfo: GLib.Object
    {
        public WebKitDOMMemoryInfo(IntPtr handle) : base(handle) { }
        // DEBUG: WEBKIT_API GTypewebkit_dom_memory_info_get_type (void)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_memory_info_get_type")]
        internal static extern uint webkit_dom_memory_info_get_type();
        public GLib.GType Type
        {
            get
            {
                return new GLib.GType((IntPtr)webkit_dom_memory_info_get_type());
            }
        }

        // DEBUG: WEBKIT_API gulongwebkit_dom_memory_info_get_total_js_heap_size(WebKitDOMMemoryInfo* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_memory_info_get_total_js_heap_size")]
        internal static extern uint webkit_dom_memory_info_get_total_js_heap_size(global::System.IntPtr self);

        // DEBUG: WEBKIT_API gulongwebkit_dom_memory_info_get_used_js_heap_size(WebKitDOMMemoryInfo* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_memory_info_get_used_js_heap_size")]
        internal static extern uint webkit_dom_memory_info_get_used_js_heap_size(global::System.IntPtr self);

        // DEBUG: WEBKIT_API gulongwebkit_dom_memory_info_get_js_heap_size_limit(WebKitDOMMemoryInfo* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_memory_info_get_js_heap_size_limit")]
        internal static extern uint webkit_dom_memory_info_get_js_heap_size_limit(global::System.IntPtr self);
    }
}
