//----------------------------------------------------------------------------
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
//----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace Webbed.Scripting.Interop
{
    // DEBUG: struct _WebKitDOMDocumentType { WebKitDOMNode parent_instance;}
    [StructLayout(LayoutKind.Explicit, Size = 16)]
    public unsafe struct _WebKitDOMDocumentType
    {
        // DEBUG: WebKitDOMNode parent_instance
        [FieldOffset(0)]
        public _WebKitDOMNode parent_instance;
    }

    // DEBUG: struct _WebKitDOMDocumentTypeClass { WebKitDOMNodeClass parent_class;}
    [StructLayout(LayoutKind.Explicit, Size = 68)]
    public unsafe struct _WebKitDOMDocumentTypeClass
    {
        // DEBUG: WebKitDOMNodeClass parent_class
        [FieldOffset(0)]
        public _WebKitDOMNodeClass parent_class;
    }

    public unsafe partial class WebKitDOMDocumentType: GLib.Object
    {
        public WebKitDOMDocumentType(IntPtr handle) : base(handle) { }
        // DEBUG: WEBKIT_API GTypewebkit_dom_document_type_get_type (void)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_document_type_get_type")]
        internal static extern uint webkit_dom_document_type_get_type();

        public GLib.GType Type
        {
            get
            {
                return new GLib.GType((IntPtr)webkit_dom_document_type_get_type());
            }
        }

        // DEBUG: WEBKIT_API gchar*webkit_dom_document_type_get_name(WebKitDOMDocumentType* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_document_type_get_name")]
        internal static extern sbyte* webkit_dom_document_type_get_name(global::System.IntPtr self);

        // DEBUG: WEBKIT_API WebKitDOMNamedNodeMap*webkit_dom_document_type_get_entities(WebKitDOMDocumentType* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_document_type_get_entities")]
        internal static extern global::System.IntPtr webkit_dom_document_type_get_entities(global::System.IntPtr self);

        // DEBUG: WEBKIT_API WebKitDOMNamedNodeMap*webkit_dom_document_type_get_notations(WebKitDOMDocumentType* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_document_type_get_notations")]
        internal static extern global::System.IntPtr webkit_dom_document_type_get_notations(global::System.IntPtr self);

        // DEBUG: WEBKIT_API gchar*webkit_dom_document_type_get_public_id(WebKitDOMDocumentType* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_document_type_get_public_id")]
        internal static extern sbyte* webkit_dom_document_type_get_public_id(global::System.IntPtr self);

        // DEBUG: WEBKIT_API gchar*webkit_dom_document_type_get_system_id(WebKitDOMDocumentType* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_document_type_get_system_id")]
        internal static extern sbyte* webkit_dom_document_type_get_system_id(global::System.IntPtr self);

        // DEBUG: WEBKIT_API gchar*webkit_dom_document_type_get_internal_subset(WebKitDOMDocumentType* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_document_type_get_internal_subset")]
        internal static extern sbyte* webkit_dom_document_type_get_internal_subset(global::System.IntPtr self);
    }
}
