//----------------------------------------------------------------------------
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
//----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace Webbed.Scripting.Interop
{
    // DEBUG: struct _WebKitDOMHTMLTableCellElement { WebKitDOMHTMLElement parent_instance;}
    [StructLayout(LayoutKind.Explicit, Size = 16)]
    public unsafe struct _WebKitDOMHTMLTableCellElement
    {
        // DEBUG: WebKitDOMHTMLElement parent_instance
        [FieldOffset(0)]
        public _WebKitDOMHTMLElement parent_instance;
    }

    // DEBUG: struct _WebKitDOMHTMLTableCellElementClass { WebKitDOMHTMLElementClass parent_class;}
    [StructLayout(LayoutKind.Explicit, Size = 68)]
    public unsafe struct _WebKitDOMHTMLTableCellElementClass
    {
        // DEBUG: WebKitDOMHTMLElementClass parent_class
        [FieldOffset(0)]
        public _WebKitDOMHTMLElementClass parent_class;
    }

    public unsafe partial class WebKitDOMHTMLTableCellElement: GLib.Object
    {
        public WebKitDOMHTMLTableCellElement(IntPtr handle) : base(handle) { }
        // DEBUG: WEBKIT_API GTypewebkit_dom_html_table_cell_element_get_type (void)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_table_cell_element_get_type")]
        internal static extern uint webkit_dom_html_table_cell_element_get_type();
        public GLib.GType Type
        {
            get
            {
                return new GLib.GType((IntPtr)webkit_dom_html_table_cell_element_get_type());
            }
        }

        // DEBUG: WEBKIT_API glongwebkit_dom_html_table_cell_element_get_cell_index(WebKitDOMHTMLTableCellElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_table_cell_element_get_cell_index")]
        internal static extern int webkit_dom_html_table_cell_element_get_cell_index(global::System.IntPtr self);

        // DEBUG: WEBKIT_API gchar*webkit_dom_html_table_cell_element_get_abbr(WebKitDOMHTMLTableCellElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_table_cell_element_get_abbr")]
        internal static extern sbyte* webkit_dom_html_table_cell_element_get_abbr(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_table_cell_element_set_abbr(WebKitDOMHTMLTableCellElement* self, const gchar* value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_table_cell_element_set_abbr")]
        internal static extern void webkit_dom_html_table_cell_element_set_abbr(global::System.IntPtr self, global::System.IntPtr value);

        // DEBUG: WEBKIT_API gchar*webkit_dom_html_table_cell_element_get_align(WebKitDOMHTMLTableCellElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_table_cell_element_get_align")]
        internal static extern sbyte* webkit_dom_html_table_cell_element_get_align(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_table_cell_element_set_align(WebKitDOMHTMLTableCellElement* self, const gchar* value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_table_cell_element_set_align")]
        internal static extern void webkit_dom_html_table_cell_element_set_align(global::System.IntPtr self, global::System.IntPtr value);

        // DEBUG: WEBKIT_API gchar*webkit_dom_html_table_cell_element_get_axis(WebKitDOMHTMLTableCellElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_table_cell_element_get_axis")]
        internal static extern sbyte* webkit_dom_html_table_cell_element_get_axis(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_table_cell_element_set_axis(WebKitDOMHTMLTableCellElement* self, const gchar* value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_table_cell_element_set_axis")]
        internal static extern void webkit_dom_html_table_cell_element_set_axis(global::System.IntPtr self, global::System.IntPtr value);

        // DEBUG: WEBKIT_API gchar*webkit_dom_html_table_cell_element_get_bg_color(WebKitDOMHTMLTableCellElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_table_cell_element_get_bg_color")]
        internal static extern sbyte* webkit_dom_html_table_cell_element_get_bg_color(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_table_cell_element_set_bg_color(WebKitDOMHTMLTableCellElement* self, const gchar* value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_table_cell_element_set_bg_color")]
        internal static extern void webkit_dom_html_table_cell_element_set_bg_color(global::System.IntPtr self, global::System.IntPtr value);

        // DEBUG: WEBKIT_API gchar*webkit_dom_html_table_cell_element_get_ch(WebKitDOMHTMLTableCellElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_table_cell_element_get_ch")]
        internal static extern sbyte* webkit_dom_html_table_cell_element_get_ch(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_table_cell_element_set_ch(WebKitDOMHTMLTableCellElement* self, const gchar* value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_table_cell_element_set_ch")]
        internal static extern void webkit_dom_html_table_cell_element_set_ch(global::System.IntPtr self, global::System.IntPtr value);

        // DEBUG: WEBKIT_API gchar*webkit_dom_html_table_cell_element_get_ch_off(WebKitDOMHTMLTableCellElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_table_cell_element_get_ch_off")]
        internal static extern sbyte* webkit_dom_html_table_cell_element_get_ch_off(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_table_cell_element_set_ch_off(WebKitDOMHTMLTableCellElement* self, const gchar* value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_table_cell_element_set_ch_off")]
        internal static extern void webkit_dom_html_table_cell_element_set_ch_off(global::System.IntPtr self, global::System.IntPtr value);

        // DEBUG: WEBKIT_API glongwebkit_dom_html_table_cell_element_get_col_span(WebKitDOMHTMLTableCellElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_table_cell_element_get_col_span")]
        internal static extern int webkit_dom_html_table_cell_element_get_col_span(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_table_cell_element_set_col_span(WebKitDOMHTMLTableCellElement* self, glong value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_table_cell_element_set_col_span")]
        internal static extern void webkit_dom_html_table_cell_element_set_col_span(global::System.IntPtr self, int value);

        // DEBUG: WEBKIT_API gchar*webkit_dom_html_table_cell_element_get_headers(WebKitDOMHTMLTableCellElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_table_cell_element_get_headers")]
        internal static extern sbyte* webkit_dom_html_table_cell_element_get_headers(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_table_cell_element_set_headers(WebKitDOMHTMLTableCellElement* self, const gchar* value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_table_cell_element_set_headers")]
        internal static extern void webkit_dom_html_table_cell_element_set_headers(global::System.IntPtr self, global::System.IntPtr value);

        // DEBUG: WEBKIT_API gchar*webkit_dom_html_table_cell_element_get_height(WebKitDOMHTMLTableCellElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_table_cell_element_get_height")]
        internal static extern sbyte* webkit_dom_html_table_cell_element_get_height(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_table_cell_element_set_height(WebKitDOMHTMLTableCellElement* self, const gchar* value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_table_cell_element_set_height")]
        internal static extern void webkit_dom_html_table_cell_element_set_height(global::System.IntPtr self, global::System.IntPtr value);

        // DEBUG: WEBKIT_API gbooleanwebkit_dom_html_table_cell_element_get_no_wrap(WebKitDOMHTMLTableCellElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_table_cell_element_get_no_wrap")]
        internal static extern int webkit_dom_html_table_cell_element_get_no_wrap(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_table_cell_element_set_no_wrap(WebKitDOMHTMLTableCellElement* self, gboolean value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_table_cell_element_set_no_wrap")]
        internal static extern void webkit_dom_html_table_cell_element_set_no_wrap(global::System.IntPtr self, int value);

        // DEBUG: WEBKIT_API glongwebkit_dom_html_table_cell_element_get_row_span(WebKitDOMHTMLTableCellElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_table_cell_element_get_row_span")]
        internal static extern int webkit_dom_html_table_cell_element_get_row_span(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_table_cell_element_set_row_span(WebKitDOMHTMLTableCellElement* self, glong value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_table_cell_element_set_row_span")]
        internal static extern void webkit_dom_html_table_cell_element_set_row_span(global::System.IntPtr self, int value);

        // DEBUG: WEBKIT_API gchar*webkit_dom_html_table_cell_element_get_scope(WebKitDOMHTMLTableCellElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_table_cell_element_get_scope")]
        internal static extern sbyte* webkit_dom_html_table_cell_element_get_scope(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_table_cell_element_set_scope(WebKitDOMHTMLTableCellElement* self, const gchar* value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_table_cell_element_set_scope")]
        internal static extern void webkit_dom_html_table_cell_element_set_scope(global::System.IntPtr self, global::System.IntPtr value);

        // DEBUG: WEBKIT_API gchar*webkit_dom_html_table_cell_element_get_v_align(WebKitDOMHTMLTableCellElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_table_cell_element_get_v_align")]
        internal static extern sbyte* webkit_dom_html_table_cell_element_get_v_align(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_table_cell_element_set_v_align(WebKitDOMHTMLTableCellElement* self, const gchar* value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_table_cell_element_set_v_align")]
        internal static extern void webkit_dom_html_table_cell_element_set_v_align(global::System.IntPtr self, global::System.IntPtr value);

        // DEBUG: WEBKIT_API gchar*webkit_dom_html_table_cell_element_get_width(WebKitDOMHTMLTableCellElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_table_cell_element_get_width")]
        internal static extern sbyte* webkit_dom_html_table_cell_element_get_width(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_table_cell_element_set_width(WebKitDOMHTMLTableCellElement* self, const gchar* value)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_table_cell_element_set_width")]
        internal static extern void webkit_dom_html_table_cell_element_set_width(global::System.IntPtr self, global::System.IntPtr value);
    }
}
