//----------------------------------------------------------------------------
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
//----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace Webbed.Scripting.Interop
{
    // DEBUG: struct _WebKitDOMHTMLFieldSetElement { WebKitDOMHTMLElement parent_instance;}
    [StructLayout(LayoutKind.Explicit, Size = 16)]
    public unsafe struct _WebKitDOMHTMLFieldSetElement
    {
        // DEBUG: WebKitDOMHTMLElement parent_instance
        [FieldOffset(0)]
        public _WebKitDOMHTMLElement parent_instance;
    }

    // DEBUG: struct _WebKitDOMHTMLFieldSetElementClass { WebKitDOMHTMLElementClass parent_class;}
    [StructLayout(LayoutKind.Explicit, Size = 68)]
    public unsafe struct _WebKitDOMHTMLFieldSetElementClass
    {
        // DEBUG: WebKitDOMHTMLElementClass parent_class
        [FieldOffset(0)]
        public _WebKitDOMHTMLElementClass parent_class;
    }

    public unsafe partial class WebKitDOMHTMLFieldSetElement: GLib.Object
    {
        public WebKitDOMHTMLFieldSetElement(IntPtr handle) : base(handle) { }
        // DEBUG: WEBKIT_API GTypewebkit_dom_html_field_set_element_get_type (void)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_field_set_element_get_type")]
        internal static extern uint webkit_dom_html_field_set_element_get_type();
        public GLib.GType Type
        {
            get
            {
                return new GLib.GType((IntPtr)webkit_dom_html_field_set_element_get_type());
            }
        }

        // DEBUG: WEBKIT_API gbooleanwebkit_dom_html_field_set_element_check_validity(WebKitDOMHTMLFieldSetElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_field_set_element_check_validity")]
        internal static extern int webkit_dom_html_field_set_element_check_validity(global::System.IntPtr self);

        // DEBUG: WEBKIT_API voidwebkit_dom_html_field_set_element_set_custom_validity(WebKitDOMHTMLFieldSetElement* self, const gchar* error)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_field_set_element_set_custom_validity")]
        internal static extern void webkit_dom_html_field_set_element_set_custom_validity(global::System.IntPtr self, global::System.IntPtr error);

        // DEBUG: WEBKIT_API WebKitDOMHTMLFormElement*webkit_dom_html_field_set_element_get_form(WebKitDOMHTMLFieldSetElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_field_set_element_get_form")]
        internal static extern global::System.IntPtr webkit_dom_html_field_set_element_get_form(global::System.IntPtr self);

        // DEBUG: WEBKIT_API WebKitDOMValidityState*webkit_dom_html_field_set_element_get_validity(WebKitDOMHTMLFieldSetElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_field_set_element_get_validity")]
        internal static extern global::System.IntPtr webkit_dom_html_field_set_element_get_validity(global::System.IntPtr self);

        // DEBUG: WEBKIT_API gbooleanwebkit_dom_html_field_set_element_get_will_validate(WebKitDOMHTMLFieldSetElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_field_set_element_get_will_validate")]
        internal static extern int webkit_dom_html_field_set_element_get_will_validate(global::System.IntPtr self);

        // DEBUG: WEBKIT_API gchar*webkit_dom_html_field_set_element_get_validation_message(WebKitDOMHTMLFieldSetElement* self)
        [SuppressUnmanagedCodeSecurity]
        [DllImport("webkitgtk-1.0", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
            EntryPoint="webkit_dom_html_field_set_element_get_validation_message")]
        internal static extern sbyte* webkit_dom_html_field_set_element_get_validation_message(global::System.IntPtr self);
    }
}
